In [2]:
import requests
import json
import pandas as pd
import time
import pprint as pp
import re

### Steps to retrieve ClickUp Data

If you want to check how the data is extracted from click up, uncomment all callable codes from the comments & run them until the next markdown

In [3]:
# config.py
CLICKUP_TOKEN = 'pk_80488909_E7HYSNIATQDY0IJF3894MGZXKGDNQAJA'
HEADERS = {"Authorization": CLICKUP_TOKEN}

# IDs - keep them in one place for easy changes
TEAM_ID = "9012223014"
BESA_SPACE_ID = "90121722741"
OPERATIONS_FOLDER_ID = "90123018368"
BESA_CLIENTS_LIST_ID = "901205091637"

USER > WORKSPACE > FOLDER > LISTS > TASKS

In [4]:
def clickup_get(endpoint, headers, params=None, delay=0.3):
    url = f"https://api.clickup.com/api/v2/{endpoint}"
    res = requests.get(url, headers=headers, params=params)
    if res.status_code != 200:
        raise Exception(f"ClickUp API error: {res.status_code} - {res.text}")
    time.sleep(delay)  # avoid rate limit
    return res.json()

In [5]:
# GET USER ID
user = clickup_get(f"user", HEADERS)
# user

In [6]:
# GET MAPOGOS TEAM ID
team = clickup_get(f"team", HEADERS)
# team

# -> Mapogos Capital has TEAM_ID: 9012223014

In [7]:
# GET BESA CONSTRUCTION WORKSPACE ID
besa_space = clickup_get(f"team/{TEAM_ID}/space", HEADERS)
# besa_space

# -> Besa Construction Workspace has BESA_SPACE_ID: 90121722741

In [8]:
# GET BESA CONSTRUCTION OPERATIONS FOLDER ID
besa_operations = clickup_get(f"space/{BESA_SPACE_ID}/folder", HEADERS)
# besa_operations

# -> Besa has OPERATIONS_FOLDER_ID: 90123018368

In [9]:
CLICKUP_TOKEN = 'pk_80488909_E7HYSNIATQDY0IJF3894MGZXKGDNQAJA'
HEADERS = {"Authorization": CLICKUP_TOKEN}

In [10]:
res = requests.get("https://api.clickup.com/api/v2/list/901205091637/task", headers=HEADERS)
res.json()

{'tasks': [{'id': '869c5pbhm',
   'custom_id': None,
   'custom_item_id': 0,
   'name': 'Simon Richardson #248',
   'text_content': '',
   'description': '',
   'status': {'status': 'completed project not paid',
    'id': 'sc901205091637_wB22ZYIo',
    'color': '#d33d44',
    'type': 'done',
    'orderindex': 4},
   'orderindex': '120302423.00009700000000000000000000000000',
   'date_created': '1771281039387',
   'date_updated': '1771614958479',
   'date_closed': None,
   'date_done': '1771595576455',
   'archived': False,
   'creator': {'id': 152482999,
    'username': 'Dardan Krasniqi ',
    'color': None,
    'email': 'contact@besaconstruction.co.uk',
    'profilePicture': None},
   'assignees': [],
   'group_assignees': [],
   'watchers': [{'id': 152482999,
     'username': 'Dardan Krasniqi ',
     'color': None,
     'initials': 'DK',
     'email': 'contact@besaconstruction.co.uk',
     'profilePicture': None},
    {'id': 80488867,
     'username': 'Nicole',
     'color': '',
     'initials': 'N',
     'email': 'msnicolebaro@gmail.com',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/80488867_lun.jpg'}],
   'checklists': [{'id': '5ce488fd-8de6-44be-99f1-9770e7b31227',
     'task_id': '869c5pbhm',
     'name': 'materiale',
     'date_created': '1771613853315',
     'orderindex': 1,
     'creator': 152482999,
     'resolved': 0,
     'unresolved': 1,
     'items': [{'id': '070bbaac-eda8-4380-880f-af749c9585aa',
       'name': '-0',
       'orderindex': 0,
       'assignee': None,
       'group_assignee': None,
       'resolved': False,
       'parent': None,
       'date_created': '1771613870527',
       'start_date': None,
       'start_date_time': False,
       'due_date': None,
       'due_date_time': False,
       'sent_due_date_notif': None,
       'children': []}]}],
   'tags': [],
   'parent': None,
   'top_level_parent': None,
   'priority': None,
   'due_date': None,
   'start_date': None,
   'points': None,
   'time_estimate': None,
   'custom_fields': [{'id': '3fee4caa-cdcf-4d79-8899-1cdac2e432f7',
     'name': '01 Dardan (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400185737',
     'hide_from_guests': False,
     'value': '0.3',
     'value_richtext': '',
     'required': False},
    {'id': 'e655b671-b568-4eef-acab-20ca7382e278',
     'name': '02 Musa (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400199723',
     'hide_from_guests': False,
     'required': False},
    {'id': 'a3627139-00be-4789-a226-609ca370ef3f',
     'name': '03 Dori (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400220732',
     'hide_from_guests': False,
     'required': False},
    {'id': 'ce6c6e78-6d34-4712-bb1a-d0260373f6a8',
     'name': '04 Remzi (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1753876499232',
     'hide_from_guests': False,
     'required': False},
    {'id': '521521ed-f3c6-476c-b5fd-072af052dae9',
     'name': 'Client Name',
     'type': 'short_text',
     'type_config': {},
     'date_created': '1753877741448',
     'hide_from_guests': False,
     'value': 'Simon Richardson',
     'value_richtext': '',
     'required': False},
    {'id': 'b92a487f-947e-491f-80f7-71241db67c32',
     'name': 'Date',
     'type': 'date',
     'type_config': {},
     'date_created': '1760875762159',
     'hide_from_guests': False,
     'required': False},
    {'id': '2d5eb854-1983-4724-8131-74244e32112c',
     'name': 'Email Address',
     'type': 'email',
     'type_config': {},
     'date_created': '1731266044799',
     'hide_from_guests': False,
     'value': 'swrichardson@gmail.com',
     'value_richtext': None,
     'required': False},
    {'id': '0fe7303e-3213-455e-ac3a-99a053d537f7',
     'name': 'How did you hear about us?',
     'type': 'drop_down',
     'type_config': {'default': 0,
      'sorting': 'manual',
      'placeholder': None,
      'new_drop_down': True,
      'options': [{'id': '279bcf59-ce1d-4027-b7fa-44592dd75a96',
        'name': 'Word Of Mouth',
        'color': '#1bbc9c',
        'orderindex': 0},
       {'id': '5ef187b9-d690-4e1f-9d20-166a4dc6d26b',
        'name': 'Online/Website',
        'color': '#81B1FF',
        'orderindex': 1},
       {'id': '1bbaaf99-0550-45a1-a838-00b4bc57a19a',
        'name': 'Existing Client',
        'color': '#FF7FAB',
        'orderindex': 2},
       {'id': '44e23537-2d1c-412a-b9aa-e5463f7fd7c2',
        'name': 'From a Friend',
        'color': '#661C11',
        'orderindex': 3},
       {'id': '832097c5-0da6-41b8-b871-e18129995c63',
        'name': 'Industry Referral',
        'color': '#f9d900',
        'orderindex': 4},
       {'id': '04a46517-d4c0-41a2-b2dc-a792bdfd57e1',
        'name': 'next door ',
        'color': '#8134B5',
        'orderindex': 5},
       {'id': '17924e54-ecc3-419c-b721-99a359214bd6',
        'name': 'Client Neighbour',
        'color': '#606199',
        'orderindex': 6}]},
     'date_created': '1729502475222',
     'hide_from_guests': False,
     'required': False},
    {'id': 'c2f254e0-4e12-4a9d-8131-f0b5488628a1',
     'name': 'Material Cost',
     'type': 'currency',
     'type_config': {'precision': 2, 'currency_type': 'GBP'},
     'date_created': '1755003551251',
     'hide_from_guests': False,
     'required': False},
    {'id': '75003c17-8dc3-4f1a-b4c0-c67f99bb9ef7',
     'name': 'Phone Number',
     'type': 'phone',
     'type_config': {},
     'date_created': '1731266023454',
     'hide_from_guests': False,
     'required': False},
    {'id': 'e32e6e6a-acf7-4ee6-af62-50e3baf13fcc',
     'name': 'Project Address',
     'type': 'short_text',
     'type_config': {},
     'date_created': '1731265998602',
     'hide_from_guests': False,
     'required': False},
    {'id': '4b4641e1-786f-418a-9fc1-c1949bb09977',
     'name': 'Service 1',
     'type': 'drop_down',
     'type_config': {'sorting': 'manual',
      'new_drop_down': True,
      'options': [{'id': '00ee07ff-cbff-4c4e-88a0-0d2d2998c44d',
        'name': 'Wall panel',
        'color': None,
        'orderindex': 0},
       {'id': '3eb6bf4c-b6bd-41b1-9e8d-29c40cd31fa7',
        'name': 'Lighting',
        'color': None,
        'orderindex': 1},
       {'id': '4931f723-e0fd-4af9-b603-0fb3ff4653fb',
        'name': 'Paint',
        'color': None,
        'orderindex': 2},
       {'id': '2eae91a2-4aa5-48c1-b582-bd5707892fd0',
        'name': 'Waterproof Rendering',
        'color': None,
        'orderindex': 3},
       {'id': '9cfdb0d1-e452-4936-a225-e6e8804243f7',
        'name': 'Tiling',
        'color': None,
        'orderindex': 4},
       {'id': '3a9f9997-93e3-4ad0-99eb-b0cfdca93eb7',
        'name': 'Garden',
        'color': None,
        'orderindex': 5},
       {'id': '7baadfc6-68b8-4b62-9bc0-ed21ab177606',
        'name': 'Electrical Work',
        'color': None,
        'orderindex': 6},
       {'id': '6c9f3ecc-4b57-4d92-9f44-a51615c07618',
        'name': 'Repair',
        'color': None,
        'orderindex': 7},
       {'id': '0803fede-6842-4f79-a154-6466e164e3c9',
        'name': 'Roofing',
        'color': None,
        'orderindex': 8},
       {'id': '588b2d5b-0e8e-417b-b73f-4c82b65a50ea',
        'name': 'Window Outside Painting',
        'color': None,
        'orderindex': 9},
       {'id': 'd402217f-6d4b-401e-bfd0-7b4bb8979ed1',
        'name': 'digging agenc wall ',
        'color': None,
        'orderindex': 10},
       {'id': 'f1289123-5897-4e68-882e-3dbc51211781',
        'name': 'paint kichen wall',
        'color': None,
        'orderindex': 11},
       {'id': 'd36b5f52-48aa-4185-8b56-be0fdf21fe81',
        'name': 'paint just living room ',
        'color': None,
        'orderindex': 12},
       {'id': '522c97d4-7a53-432d-a06d-5d726bb5ff05',
        'name': 'replace wc',
        'color': None,
        'orderindex': 13},
       {'id': '6862c4fb-dcd7-4f3d-b1b6-29bcc5706588',
        'name': 'post fenc',
        'color': None,
        'orderindex': 14},
       {'id': '2596bf06-a04d-4a47-9a7e-96facb963e25',
        'name': 'level graand ',
        'color': None,
        'orderindex': 15},
       {'id': 'e8b7b114-4d65-4561-a1d3-59d10f66223d',
        'name': 'wood work',
        'color': None,
        'orderindex': 16},
       {'id': '7f5c4868-cced-4c18-86ea-8a7f38568e74',
        'name': 'concrete base',
        'color': None,
        'orderindex': 17},
       {'id': 'f10e5c5c-e62c-4d14-9da3-67ca1eb116c2',
        'name': 'plasterbourds',
        'color': None,
        'orderindex': 18},
       {'id': '10329929-a208-4b2f-9d0f-0ae7f6f4dcd2',
        'name': 'loft bedroom to do all work internel ',
        'color': None,
        'orderindex': 19},
       {'id': '31b5a141-08db-49ff-ba85-63bd61d45e96',
        'name': 'selicon wall gup emergenci',
        'color': None,
        'orderindex': 20},
       {'id': 'f96b48e8-4f4b-431b-b663-7509dc9a1b27',
        'name': 'open wall for breakfast bar',
        'color': None,
        'orderindex': 21},
       {'id': '26ebca4a-fb90-4f05-8e3e-01303118e7fb',
        'name': 'assemble cage',
        'color': None,
        'orderindex': 22},
       {'id': '1ffda17b-eb95-4902-a2d0-2f672ffb7134',
        'name': 'kitchen vent pipe',
        'color': None,
        'orderindex': 23},
       {'id': '17faa7ea-31bf-45c7-a019-2d3b273e6aaf',
        'name': 'dado railing wc ',
        'color': None,
        'orderindex': 24},
       {'id': '7d098cdc-a330-4f68-8585-e2241dc0fb7b',
        'name': 'roff on extension replase',
        'color': None,
        'orderindex': 25},
       {'id': '0e0f0ddc-5634-4483-b6ed-a39ecb50d0d1',
        'name': 'BUILD WERDROP BEDROOM ',
        'color': None,
        'orderindex': 26},
       {'id': '8f309912-bea0-47be-bf88-62e9a3566afc',
        'name': 'PAINTING',
        'color': None,
        'orderindex': 27},
       {'id': '91038368-00b9-42a9-b63a-5176d8d2b56a',
        'name': 'PAINT WALL AND CELING',
        'color': None,
        'orderindex': 28},
       {'id': '1e65c150-efff-440d-8269-00893d91b7d1',
        'name': 'lighting replase',
        'color': None,
        'orderindex': 29},
       {'id': '2ceb88ef-c38d-4bc4-b858-f3fefe993f80',
        'name': 'PLASTER',
        'color': None,
        'orderindex': 30},
       {'id': 'bc6ef384-c63b-42ba-a514-c57b17deabcf',
        'name': 'PAINT HALLWAY 4 STORY FLOOR',
        'color': None,
        'orderindex': 31},
       {'id': '2d7e6e3d-8765-448a-b0ca-b8fc447e4603',
        'name': 'instol ne kichen ',
        'color': None,
        'orderindex': 32},
       {'id': 'ce9dd1b1-a3d2-4e7b-83ab-1ffa4360ebe0',
        'name': 'BATHROOM',
        'color': None,
        'orderindex': 33},
       {'id': '9df457f2-68fa-4c66-8c86-fe310943db5a',
        'name': 'WATER ',
        'color': None,
        'orderindex': 34},
       {'id': 'aeeebbba-5a3b-4f0c-a446-20a6a697c954',
        'name': 'FIXING DOOR',
        'color': None,
        'orderindex': 35},
       {'id': 'bf9e37fe-6947-47db-aa41-adca7d031e8d',
        'name': 'removing furniture',
        'color': None,
        'orderindex': 36},
       {'id': '9f78aff2-f745-4f32-a65d-545caf11bf8f',
        'name': 'sash window',
        'color': None,
        'orderindex': 37},
       {'id': '7f2e8d1e-0874-4254-b8ae-55a1b6bc83aa',
        'name': 'bathroom refurbishment',
        'color': None,
        'orderindex': 38},
       {'id': '2970e8a4-8133-4640-adc0-70b7a6d6e66c',
        'name': 'maintenace',
        'color': None,
        'orderindex': 39},
       {'id': '0a684f24-27ce-4bde-91bc-e2efa7ddd460',
        'name': 'brick work',
        'color': None,
        'orderindex': 40},
       {'id': '7b030495-d8fb-4cff-8c32-24cdb161bd0f',
        'name': 'REAR EXTENSIONS AND SIDE EXTENSION',
        'color': None,
        'orderindex': 41},
       {'id': '4f6b8747-b417-4c79-8ba3-feb68c272774',
        'name': 'WINDOW PAINTING ',
        'color': None,
        'orderindex': 42},
       {'id': 'a54be6b2-2fdf-41a9-baaf-34eae704a0c5',
        'name': 'renovetion house',
        'color': None,
        'orderindex': 43},
       {'id': '230984c1-b2d1-4cc1-85f1-814e7a6b23cb',
        'name': 'SHELFING ',
        'color': None,
        'orderindex': 44},
       {'id': 'bda8c26d-b45c-4ab8-a424-f6625f084f61',
        'name': 'GENERAL WORK',
        'color': None,
        'orderindex': 45},
       {'id': '3b7bb0b0-6294-4402-8da5-11252be137d1',
        'name': 'FRONT DESCK ',
        'color': None,
        'orderindex': 46},
       {'id': '6db89e81-3c63-45a1-858a-2fc81509a72e',
        'name': 'PAINTING FENCING ',
        'color': None,
        'orderindex': 47},
       {'id': '589b1eeb-0706-4a39-8050-c7f8e6e4c9d7',
        'name': 'RENDERING & TILE ',
        'color': None,
        'orderindex': 48},
       {'id': '81b42f53-166c-4e96-8602-774d29c24f3f',
        'name': 'PLASTERING AND DOWN PIPE GATERING',
        'color': None,
        'orderindex': 49},
       {'id': 'b5570afc-d085-4c44-b500-96ce286029df',
        'name': 'GUTTERING ,POINTING ,PLUMBING ,ROFF TILE ',
        'color': None,
        'orderindex': 50},
       {'id': 'b54722b7-b157-46a1-9b4f-7bad1c264449',
        'name': 'painting and rendering ',
        'color': None,
        'orderindex': 51},
       {'id': 'ee176564-701a-4cdb-b399-fa76e8b6da12',
        'name': 'BIN STORE ',
        'color': None,
        'orderindex': 52},
       {'id': 'a2e4cf5c-1746-4afa-8663-bcbc34fad1d1',
        'name': 'RENDERING  ',
        'color': None,
        'orderindex': 53},
       {'id': 'f4b9578a-5e3b-43aa-9eb0-edc3e083157a',
        'name': 'install radiator ',
        'color': None,
        'orderindex': 54}]},
     'date_created': '1729962191784',
     'hide_from_guests': False,
     'required': False},
    {'id': '9307229f-f523-4237-852f-d0976cd3b184',
     'name': 'Total Price (excl. VAT%)',
     'type': 'currency',
     'type_config': {'precision': 2, 'currency_type': 'GBP'},
     'date_created': '1729934894881',
     'hide_from_guests': False,
     'value': '580',
     'value_richtext': '',
     'required': False}],
   'dependencies': [],
   'linked_tasks': [],
   'locations': [],
   'team_id': '9012223014',
   'url': 'https://app.clickup.com/t/869c5pbhm',
   'sharing': {'public': False,
    'public_share_expires_on': None,
    'public_fields': ['assignees',
     'priority',
     'due_date',
     'content',
     'comments',
     'attachments',
     'customFields',
     'subtasks',
     'tags',
     'checklists',
     'coverimage'],
    'token': None,
    'seo_optimized': False},
   'permission_level': 'create',
   'list': {'id': '901205091637', 'name': 'Besa Clients', 'access': True},
   'project': {'id': '90123018368',
    'name': 'Operations',
    'hidden': False,
    'access': True},
   'folder': {'id': '90123018368',
    'name': 'Operations',
    'hidden': False,
    'access': True},
   'space': {'id': '90121722741'}},
  {'id': '869c593gv',
   'custom_id': None,
   'custom_item_id': 0,
   'name': 'The Brown Cow Pub 🤝',
   'text_content': 'This seems like a business who is ran by smart and friendly people management. \n\nI predict a large amount of Fulham business owners will show up at that Pub. This is because the Brown Cow Pub is offering free meeting room on Mondays and Tuesdays. \n\nIt is worth reaching to Carnell and have a meeting with her to establish some form of a deal with Besa to generate organic leads through the pub.',
   'description': 'This seems like a business who is ran by smart and friendly people management. \n\nI predict a large amount of Fulham business owners will show up at that Pub. This is because the Brown Cow Pub is offering free meeting room on Mondays and Tuesdays. \n\nIt is worth reaching to Carnell and have a meeting with her to establish some form of a deal with Besa to generate organic leads through the pub.',
   'status': {'status': 'warm lead',
    'id': 'sc901205091637_Pf6AbMhD',
    'color': '#e16b16',
    'type': 'open',
    'orderindex': 0},
   'orderindex': '120302418.00000000000000000000000000000000',
   'date_created': '1771242644029',
   'date_updated': '1771608887692',
   'date_closed': None,
   'date_done': None,
   'archived': False,
   'creator': {'id': 4715679,
    'username': 'Adhurim Doci',
    'color': '',
    'email': 'adhurim.doci.uk@gmail.com',
    'profilePicture': 'https://attachments.clickup.com/profilePictures/4715679_ZYx.jpg'},
   'assignees': [{'id': 80488867,
     'username': 'Nicole',
     'color': '',
     'initials': 'N',
     'email': 'msnicolebaro@gmail.com',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/80488867_lun.jpg'},
    {'id': 152482999,
     'username': 'Dardan Krasniqi ',
     'color': None,
     'initials': 'DK',
     'email': 'contact@besaconstruction.co.uk',
     'profilePicture': None}],
   'group_assignees': [],
   'watchers': [{'id': 80488895,
     'username': 'Angelo Desouza',
     'color': '',
     'initials': 'AD',
     'email': 'angelodesouza2020@gmail.com',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/80488895_J6P.jpg'},
    {'id': 4715679,
     'username': 'Adhurim Doci',
     'color': '',
     'initials': 'AD',
     'email': 'adhurim.doci.uk@gmail.com',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/4715679_ZYx.jpg'},
    {'id': 80488867,
     'username': 'Nicole',
     'color': '',
     'initials': 'N',
     'email': 'msnicolebaro@gmail.com',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/80488867_lun.jpg'},
    {'id': 152482999,
     'username': 'Dardan Krasniqi ',
     'color': None,
     'initials': 'DK',
     'email': 'contact@besaconstruction.co.uk',
     'profilePicture': None},
    {'id': 4714367,
     'username': 'Damian Adamski',
     'color': '#0091ff',
     'initials': 'DA',
     'email': 'damianadamski.uk@gmail.com',
     'profilePicture': None}],
   'checklists': [{'id': 'ec844cf2-d7c3-4353-bd81-d330be111932',
     'task_id': '869c593gv',
     'name': 'Checklist',
     'date_created': '1771242875779',
     'orderindex': 1,
     'creator': 4715679,
     'resolved': 0,
     'unresolved': 0,
     'items': []}],
   'tags': [],
   'parent': None,
   'top_level_parent': None,
   'priority': None,
   'due_date': None,
   'start_date': None,
   'points': None,
   'time_estimate': None,
   'custom_fields': [{'id': '3fee4caa-cdcf-4d79-8899-1cdac2e432f7',
     'name': '01 Dardan (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400185737',
     'hide_from_guests': False,
     'required': False},
    {'id': 'e655b671-b568-4eef-acab-20ca7382e278',
     'name': '02 Musa (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400199723',
     'hide_from_guests': False,
     'required': False},
    {'id': 'a3627139-00be-4789-a226-609ca370ef3f',
     'name': '03 Dori (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1730400220732',
     'hide_from_guests': False,
     'required': False},
    {'id': 'ce6c6e78-6d34-4712-bb1a-d0260373f6a8',
     'name': '04 Remzi (days worked)',
     'type': 'number',
     'type_config': {},
     'date_created': '1753876499232',
     'hide_from_guests': False,
     'required': False},
    {'id': '521521ed-f3c6-476c-b5fd-072af052dae9',
     'name': 'Client Name',
     'type': 'short_text',
     'type_config': {},
     'date_created': '1753877741448',
     'hide_from_guests': False,
     'required': False},
    {'id': 'b92a487f-947e-491f-80f7-71241db67c32',
     'name': 'Date',
     'type': 'date',
     'type_config': {},
     'date_created': '1760875762159',
     'hide_from_guests': False,
     'required': False},
    {'id': '2d5eb854-1983-4724-8131-74244e32112c',
     'name': 'Email Address',
     'type': 'email',
     'type_config': {},
     'date_created': '1731266044799',
     'hide_from_guests': False,
     'required': False},

In [27]:
# GET BESA CLIENTS LIST FROM OPERATIONS FOLDER
besa_client_list = clickup_get(f"folder/{OPERATIONS_FOLDER_ID}/list", HEADERS)

# -> Besa has BESA_CLIENTS_LIST_ID : 901205091637

#### RETRIEVE ALL BESA PROJECTS

In [26]:
# GET ALL PROJECTS/TASKS FROM BESA CLIENTS FOLDER
tasks = clickup_get(f"list/{BESA_CLIENTS_LIST_ID}/task", HEADERS)["tasks"]

In [13]:
for task in tasks:
    if task['id'] == '869a4xzde':
        print(task['text_content'])

Date
Dardan Labor
Musa Labor
REMZI
Dori Labor
Daily Progress
 16.08.25
 in
 off

 in
set up
 18.08.25
 in
 off

 in
protection
 19.08.25
 in
 in

 in
-
20.08.25
 in
 in

 in
-
21.08.25
in
in

in
-
22.08.25
in
in

in
painting
23.08.25
in
in

in
painting
25.08.25
in
in

in
painting
26.08.25
in
in

in
painting
27.08.25
off
off

off
-
28.08.25
in
in

in
painting
29.08.25
in
in

in
painting
30.08.25
in
in

in
painting
31.08.25
in
in

in
painting
05.09.25
IN
IN

IN
PAINTING
06.09.25
IN
IN

IN
PAINTING
07.09.25
in
in

in
painting
08.09.25
IN
IN

IN
PAINTING
09.09.25
IN
IN
IN
IN
PAINTING
10.09.25
IN
IN
IN
IN
PAINTING
11.09.25
in
in
in
in
painting
12.09.25


in


15.09.25
IN
IN
IN
HOLLIDAY
PAINTING
16.09.25
IN
IN



17.09.25
in

### NOW ADDING MODULARITY

In [14]:
# extract.py
from api import clickup_get
from config import HEADERS
import re
 
# get_paid_invoice_tasks prints all the paid invoice project ids line by line
def get_all_tasks(list_id):
    # to return just paid invoices
    tasks = clickup_get(f"list/{list_id}/task", HEADERS)["tasks"]
    return [t for t in tasks]

def get_task_details(task_ids):
    details = []
    for task_id in task_ids:
        details.append(clickup_get(f"task/{task_id}", HEADERS))
    return details

def get_subtasks(list_id):
    subtasks = []
    tasks_with_subtasks = clickup_get(
        f"list/{list_id}/task",
        HEADERS,
        params={"subtasks": "true"}
    )["tasks"]
    for task in tasks_with_subtasks:
        if task.get("parent"):  # this task is a subtask
            subtasks.append(task)
    return subtasks

def get_task_texts(tasks):
    """
    Retrieves the 'text_content' (or fallback 'description')
    for ALL tasks in the list.
    Returns a dict {task_id: text_content}.
    """
    results = {}
    for task in tasks:
        text = task.get('text_content') or task.get('description') or ""
        results[task['id']] = text
    return results

import pandas as pd

def labor_text_to_table(labor_text, task_id):
    """
    Converts labor activity text into a structured DataFrame.
    Assumes format:
        Date
        Dardan Labor
        Musa Labor
        Dori Labor
        Daily Progress
        <rows in multiples of 5>
    """
    # Split lines and remove empty lines
    lines = [line.strip() for line in labor_text.splitlines() if line.strip()]

    if len(lines) < 6:
        return pd.DataFrame()  # not enough data to form a table

    # Header
    header = lines[:5]
    rows = lines[5:]

    # Group rows by 5
    data = [rows[i:i+5] for i in range(0, len(rows), 5)]

    # Build DataFrame
    df = pd.DataFrame(data, columns=header)

    # Clean strings
    df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

    # Attach project_id
    df["project_id"] = task_id

    return df

In [15]:
all_tasks = get_all_tasks(BESA_CLIENTS_LIST_ID)
paid_tasks = [t for t in all_tasks if t["status"]["status"].lower() == "paid invoice"]
ongoing_tasks = [t for t in all_tasks if t["status"]["status"].lower() == "ongoing"]

In [ ]:
labor_text = get_task_texts(ongoing_tasks)

{'869b1hnkk': 'Date\nDardan Labor\nMusa Labor\nDori Labor \nDaily Progress\n\xa019.01.26\n\xa0in\n\xa0in\n\xa0of\n\xa0sti=ripin wal\n\xa020.01.25\n\xa0in\n\xa0in\n\xa0in\n\xa0striping wall primer\n\xa021.01.25\n\xa0in\n\xa0in\n\xa0in\n\xa0door and electrick\n\xa022.01.25\n\xa0in\n\xa0in\n\xa0in\n\xa0pointing and paint \n23.01.25\nin\nin\nin\npaint wall\n24.01.25\n\nin\nin\npaint wall\n28.01.25\nin\nin\noff\nlead & paint wall\n29.01.25\nin\nin\nin\ncctv.guttering .front wall filler \n30.01.25\nin 0.5\nin 0.5\nin 0.5\nwindow kitchen \n02.02.25\nin\nin\nin\nbath & bed window \n09.02.26\n0.5\n0.5\n0.5',
 '869ar19y7': ''}

paid_tasks → "summary" tasks from the list query.

detailed_tasks → "full task details" fetched individually.

All BESA PROJECT IDs

In [17]:
# Retrieve all the task_details, all of them will take a very long time
detailed_tasks = get_task_details([t["id"] for t in paid_tasks])
detailed_tasks

[{'id': '869c1tu79',
  'custom_id': None,
  'custom_item_id': 0,
  'name': 'PARSONS NOSE  (Putney) #246',
  'text_content': '',
  'description': '',
  'status': {'id': 'sc901205091637_xkyptcu1',
   'status': 'paid invoice',
   'color': '#008844',
   'orderindex': 5,
   'type': 'done'},
  'orderindex': '120302364.00016050000000000000000000000000',
  'date_created': '1770311423708',
  'date_updated': '1770654140797',
  'date_closed': None,
  'date_done': '1770311423708',
  'archived': False,
  'creator': {'id': 152482999,
   'username': 'Dardan Krasniqi ',
   'color': None,
   'email': 'contact@besaconstruction.co.uk',
   'profilePicture': None},
  'assignees': [],
  'group_assignees': [],
  'watchers': [{'id': 80488867,
    'username': 'Nicole',
    'color': '',
    'initials': 'N',
    'email': 'msnicolebaro@gmail.com',
    'profilePicture': 'https://attachments.clickup.com/profilePictures/80488867_lun.jpg'},
   {'id': 152482999,
    'username': 'Dardan Krasniqi ',
    'color': None,
    'initials': 'DK',
    'email': 'contact@besaconstruction.co.uk',
    'profilePicture': None}],
  'checklists': [{'id': '01f3d372-9e91-45df-9789-473a6f7034d8',
    'task_id': '869c1tu79',
    'name': 'Checklist',
    'date_created': '1770313259242',
    'orderindex': 1,
    'creator': 152482999,
    'resolved': 0,
    'unresolved': 2,
    'items': [{'id': '7b73544e-9f46-46ea-ba74-5227d876663f',
      'name': 'hps boiler -312.72',
      'orderindex': 0,
      'assignee': None,
      'group_assignee': None,
      'resolved': False,
      'parent': None,
      'date_created': '1770313345555',
      'start_date': None,
      'start_date_time': False,
      'due_date': None,
      'due_date_time': False,
      'sent_due_date_notif': None,
      'children': []},
     {'id': '773065a3-4613-45e1-925f-2d55691b5674',
      'name': 'travis perkings -12.92',
      'orderindex': 1,
      'assignee': None,
      'group_assignee': None,
      'resolved': False,
      'parent': None,
      'date_created': '1770313379223',
      'start_date': None,
      'start_date_time': False,
      'due_date': None,
      'due_date_time': False,
      'sent_due_date_notif': None,
      'children': []}]},
   {'id': '72509913-ba28-4fe4-aff8-63e1fad2575c',
    'task_id': '869c1tu79',
    'name': 'material',
    'date_created': '1770313114100',
    'orderindex': 1,
    'creator': 152482999,
    'resolved': 0,
    'unresolved': 0,
    'items': []}],
  'tags': [],
  'parent': None,
  'top_level_parent': None,
  'priority': None,
  'due_date': None,
  'start_date': None,
  'points': None,
  'time_estimate': None,
  'time_spent': 0,
  'custom_fields': [{'id': '3fee4caa-cdcf-4d79-8899-1cdac2e432f7',
    'name': '01 Dardan (days worked)',
    'type': 'number',
    'type_config': {},
    'date_created': '1730400185737',
    'hide_from_guests': False,
    'value': '0.5',
    'value_richtext': '',
    'required': False},
   {'id': 'e655b671-b568-4eef-acab-20ca7382e278',
    'name': '02 Musa (days worked)',
    'type': 'number',
    'type_config': {},
    'date_created': '1730400199723',
    'hide_from_guests': False,
    'required': False},
   {'id': 'a3627139-00be-4789-a226-609ca370ef3f',
    'name': '03 Dori (days worked)',
    'type': 'number',
    'type_config': {},
    'date_created': '1730400220732',
    'hide_from_guests': False,
    'value': '0.5',
    'value_richtext': '',
    'required': False},
   {'id': 'ce6c6e78-6d34-4712-bb1a-d0260373f6a8',
    'name': '04 Remzi (days worked)',
    'type': 'number',
    'type_config': {},
    'date_created': '1753876499232',
    'hide_from_guests': False,
    'required': False},
   {'id': '521521ed-f3c6-476c-b5fd-072af052dae9',
    'name': 'Client Name',
    'type': 'short_text',
    'type_config': {},
    'date_created': '1753877741448',
    'hide_from_guests': False,
    'required': False},
   {'id': 'b92a487f-947e-491f-80f7-71241db67c32',
    'name': 'Date',
    'type': 'date',
    'type_config': {},
    'date_created': '1760875762159',
    'hide_from_guests': False,
    'required': False},
   {'id': '2d5eb854-1983-4724-8131-74244e32112c',
    'name': 'Email Address',
    'type': 'email',
    'type_config': {},
    'date_created': '1731266044799',
    'hide_from_guests': False,
    'required': False},
   {'id': '0fe7303e-3213-455e-ac3a-99a053d537f7',
    'name': 'How did you hear about us?',
    'type': 'drop_down',
    'type_config': {'default': 0,
     'sorting': 'manual',
     'placeholder': None,
     'new_drop_down': True,
     'options': [{'id': '279bcf59-ce1d-4027-b7fa-44592dd75a96',
       'name': 'Word Of Mouth',
       'color': '#1bbc9c',
       'orderindex': 0},
      {'id': '5ef187b9-d690-4e1f-9d20-166a4dc6d26b',
       'name': 'Online/Website',
       'color': '#81B1FF',
       'orderindex': 1},
      {'id': '1bbaaf99-0550-45a1-a838-00b4bc57a19a',
       'name': 'Existing Client',
       'color': '#FF7FAB',
       'orderindex': 2},
      {'id': '44e23537-2d1c-412a-b9aa-e5463f7fd7c2',
       'name': 'From a Friend',
       'color': '#661C11',
       'orderindex': 3},
      {'id': '832097c5-0da6-41b8-b871-e18129995c63',
       'name': 'Industry Referral',
       'color': '#f9d900',
       'orderindex': 4},
      {'id': '04a46517-d4c0-41a2-b2dc-a792bdfd57e1',
       'name': 'next door ',
       'color': '#8134B5',
       'orderindex': 5},
      {'id': '17924e54-ecc3-419c-b721-99a359214bd6',
       'name': 'Client Neighbour',
       'color': '#606199',
       'orderindex': 6}]},
    'date_created': '1729502475222',
    'hide_from_guests': False,
    'required': False},
   {'id': 'c2f254e0-4e12-4a9d-8131-f0b5488628a1',
    'name': 'Material Cost',
    'type': 'currency',
    'type_config': {'precision': 2, 'currency_type': 'GBP'},
    'date_created': '1755003551251',
    'hide_from_guests': False,
    'value': '325.64',
    'value_richtext': '',
    'required': False},
   {'id': '75003c17-8dc3-4f1a-b4c0-c67f99bb9ef7',
    'name': 'Phone Number',
    'type': 'phone',
    'type_config': {},
    'date_created': '1731266023454',
    'hide_from_guests': False,
    'required': False},
   {'id': 'e32e6e6a-acf7-4ee6-af62-50e3baf13fcc',
    'name': 'Project Address',
    'type': 'short_text',
    'type_config': {},
    'date_created': '1731265998602',
    'hide_from_guests': False,
    'required': False},
   {'id': '4b4641e1-786f-418a-9fc1-c1949bb09977',
    'name': 'Service 1',
    'type': 'drop_down',
    'type_config': {'sorting': 'manual',
     'new_drop_down': True,
     'options': [{'id': '00ee07ff-cbff-4c4e-88a0-0d2d2998c44d',
       'name': 'Wall panel',
       'color': None,
       'orderindex': 0},
      {'id': '3eb6bf4c-b6bd-41b1-9e8d-29c40cd31fa7',
       'name': 'Lighting',
       'color': None,
       'orderindex': 1},
      {'id': '4931f723-e0fd-4af9-b603-0fb3ff4653fb',
       'name': 'Paint',
       'color': None,
       'orderindex': 2},
      {'id': '2eae91a2-4aa5-48c1-b582-bd5707892fd0',
       'name': 'Waterproof Rendering',
       'color': None,
       'orderindex': 3},
      {'id': '9cfdb0d1-e452-4936-a225-e6e8804243f7',
       'name': 'Tiling',
       'color': None,
       'orderindex': 4},
      {'id': '3a9f9997-93e3-4ad0-99eb-b0cfdca93eb7',
       'name': 'Garden',
       'color': None,
       'orderindex': 5},
      {'id': '7baadfc6-68b8-4b62-9bc0-ed21ab177606',
       'name': 'Electrical Work',
       'color': None,
       'orderindex': 6},
      {'id': '6c9f3ecc-4b57-4d92-9f44-a51615c07618',
       'name': 'Repair',
       'color': None,
       'orderindex': 7},
      {'id': '0803fede-6842-4f79-a154-6466e164e3c9',
       'name': 'Roofing',
       'color': None,
       'orderindex': 8},
      {'id': '588b2d5b-0e8e-417b-b73f-4c82b65a50ea',
       'name': 'Window Outside Painting',
       'color': None,
       'orderindex': 9},
      {'id': 'd402217f-6d4b-401e-bfd0-7b4bb8979ed1',
       'name': 'digging agenc wall ',
       'color': None,
       'orderindex': 10},
      {'id': 'f1289123-5897-4e68-882e-3dbc51211781',
       'name': 'paint kichen wall',
       'color': None,
       'orderindex': 11},
      {'id': 'd36b5f52-48aa-4185-8b56-be0fdf21fe81',
       'name': 'paint just living room ',
       'color': None,
       'orderindex': 12},
      {'id': '522c97d4-7a53-432d-a06d-5d726bb5ff05',
       'name': 'replace wc',
       'color': None,
       'orderindex': 13},
      {'id': '6862c4fb-dcd7-4f3d-b1b6-29bcc5706588',
       'name': 'post fenc',
       'color': None,
       'orderindex': 14},
      {'id': '2596bf06-a04d-4a47-9a7e-96facb963e25',
       'name': 'level graand ',
       'color': None,
       'orderindex': 15},
      {'id': 'e8b7b114-4d65-4561-a1d3-59d10f66223d',
       'name': 'wood work',
       'color': None,
       'orderindex': 16},
      {'id': '7f5c4868-cced-4c18-86ea-8a7f38568e74',
       'name': 'concrete base',
       'color': None,
       'orderindex': 17},
      {'id': 'f10e5c5c-e62c-4d14-9da3-67ca1eb116c2',
       'name': 'plasterbourds',
       'color': None,
       'orderindex': 18},
      {'id': '10329929-a208-4b2f-9d0f-0ae7f6f4dcd2',
       'name': 'loft bedroom to do all work internel ',
       'color': None,
       'orderindex': 19},
      {'id': '31b5a141-08db-49ff-ba85-63bd61d45e96',
       'name': 'selicon wall gup emergenci',
       'color': None,
       'orderindex': 20},
      {'id': 'f96b48e8-4f4b-431b-b663-7509dc9a1b27',
       'name': 'open wall for breakfast bar',
       'color': None,
       'orderindex': 21},
      {'id': '26ebca4a-fb90-4f05-8e3e-01303118e7fb',
       'name': 'assemble cage',
       'color': None,
       'orderindex': 22},
      {'id': '1ffda17b-eb95-4902-a2d0-2f672ffb7134',
       'name': 'kitchen vent pipe',
       'color': None,
       'orderindex': 23},
      {'id': '17faa7ea-31bf-45c7-a019-2d3b273e6aaf',
       'name': 'dado railing wc ',
       'color': None,
       'orderindex': 24},
      {'id': '7d098cdc-a330-4f68-8585-e2241dc0fb7b',
       'name': 'roff on extension replase',
       'color': None,
       'orderindex': 25},
      {'id': '0e0f0ddc-5634-4483-b6ed-a39ecb50d0d1',
       'name': 'BUILD WERDROP BEDROOM ',
       'color': None,
       'orderindex': 26},
      {'id': '8f309912-bea0-47be-bf88-62e9a3566afc',
       'name': 'PAINTING',
       'color': None,
       'orderindex': 27},
      {'id': '91038368-00b9-42a9-b63a-5176d8d2b56a',
       'name': 'PAINT WALL AND CELING',
       'color': None,
       'orderindex': 28},
      {'id': '1e65c150-efff-440d-8269-00893d91b7d1',
       'name': 'lighting replase',
       'color': None,
       'orderindex': 29},
      {'id': '2ceb88ef-c38d-4bc4-b858-f3fefe993f80',
       'name': 'PLASTER',
       'color': None,
       'orderindex': 30},
      {'id': 'bc6ef384-c63b-42ba-a514-c57b17deabcf',
       'name': 'PAINT HALLWAY 4 STORY FLOOR',
       'color': None,
       'orderindex': 31},
      {'id': '2d7e6e3d-8765-448a-b0ca-b8fc447e4603',
       'name': 'instol ne kichen ',
       'color': None,
       'orderindex': 32},
      {'id': 'ce9dd1b1-a3d2-4e7b-83ab-1ffa4360ebe0',
       'name': 'BATHROOM',
       'color': None,
       'orderindex': 33},
      {'id': '9df457f2-68fa-4c66-8c86-fe310943db5a',
       'name': 'WATER ',
       'color': None,
       'orderindex': 34},
      {'id': 'aeeebbba-5a3b-4f0c-a446-20a6a697c954',
       'name': 'FIXING DOOR',
       'color': None,
       'orderindex': 35},
      {'id': 'bf9e37fe-6947-47db-aa41-adca7d031e8d',
       'name': 'removing furniture',
       'color': None,
       'orderindex': 36},
      {'id': '9f78aff2-f745-4f32-a65d-545caf11bf8f',
       'name': 'sash window',
       'color': None,
       'orderindex': 37},
      {'id': '7f2e8d1e-0874-4254-b8ae-55a1b6bc83aa',
       'name': 'bathroom refurbishment',
       'color': None,
       'orderindex': 38},
      {'id': '2970e8a4-8133-4640-adc0-70b7a6d6e66c',
       'name': 'maintenace',
       'color': None,
       'orderindex': 39},
      {'id': '0a684f24-27ce-4bde-91bc-e2efa7ddd460',
       'name': 'brick work',
       'color': None,
       'orderindex': 40},
      {'id': '7b030495-d8fb-4cff-8c32-24cdb161bd0f',
       'name': 'REAR EXTENSIONS AND SIDE EXTENSION',
       'color': None,
       'orderindex': 41},
      {'id': '4f6b8747-b417-4c79-8ba3-feb68c272774',
       'name': 'WINDOW PAINTING ',
       'color': None,
       'orderindex': 42},
      {'id': 'a54be6b2-2fdf-41a9-baaf-34eae704a0c5',
       'name': 'renovetion house',
       'color': None,
       'orderindex': 43},
      {'id': '230984c1-b2d1-4cc1-85f1-814e7a6b23cb',
       'name': 'SHELFING ',
       'color': None,
       'orderindex': 44},
      {'id': 'bda8c26d-b45c-4ab8-a424-f6625f084f61',
       'name': 'GENERAL WORK',
       'color': None,
       'orderindex': 45},
      {'id': '3b7bb0b0-6294-4402-8da5-11252be137d1',
       'name': 'FRONT DESCK ',
       'color': None,
       'orderindex': 46},
      {'id': '6db89e81-3c63-45a1-858a-2fc81509a72e',
       'name': 'PAINTING FENCING ',
       'color': None,
       'orderindex': 47},
      {'id': '589b1eeb-0706-4a39-8050-c7f8e6e4c9d7',
       'name': 'RENDERING & TILE ',
       'color': None,
       'orderindex': 48},
      {'id': '81b42f53-166c-4e96-8602-774d29c24f3f',
       'name': 'PLASTERING AND DOWN PIPE GATERING',
       'color': None,
       'orderindex': 49},
      {'id': 'b5570afc-d085-4c44-b500-96ce286029df',
       'name': 'GUTTERING ,POINTING ,PLUMBING ,ROFF TILE ',
       'color': None,
       'orderindex': 50},
      {'id': 'b54722b7-b157-46a1-9b4f-7bad1c264449',
       'name': 'painting and rendering ',
       'color': None,
       'orderindex': 51},
      {'id': 'ee176564-701a-4cdb-b399-fa76e8b6da12',
       'name': 'BIN STORE ',
       'color': None,
       'orderindex': 52},
      {'id': 'a2e4cf5c-1746-4afa-8663-bcbc34fad1d1',
       'name': 'RENDERING  ',
       'color': None,
       'orderindex': 53},
      {'id': 'f4b9578a-5e3b-43aa-9eb0-edc3e083157a',
       'name': 'install radiator ',
       'color': None,
       'orderindex': 54}]},
    'date_created': '1729962191784',
    'hide_from_guests': False,
    'required': False},
   {'id': '9307229f-f523-4237-852f-d0976cd3b184',
    'name': 'Total Price (excl. VAT%)',
    'type': 'currency',
    'type_config': {'precision': 2, 'currency_type': 'GBP'},
    'date_created': '1729934894881',
    'hide_from_guests': False,
    'value': '662.72',
    'value_richtext': '',
    'required': False}],
  'dependencies': [],
  'linked_tasks': [],
  'locations': [],
  'team_id': '9012223014',
  'url': 'https://app.clickup.com/t/869c1tu79',
  'sharing': {'public': False,
   'public_share_expires_on': None,
   'public_fields': ['assignees',
    'priority',
    'due_date',
    'content',
    'comments',
    'attachments',
    'customFields',
    'subtasks',
    'tags',
    'checklists',
    'coverimage'],
   'token': None,
   'seo_optimized': False},
  'permission_level': 'create',
  'list': {'id': '901205091637', 'name': 'Besa Clients', 'access': True},
  'project': {'id': '90123018368',
   'name': 'Operations',
   'hidden': False,
   'access': True},
  'folder': {'id': '90123018368',
   'name': 'Operations',
   'hidden': False,
   'access': True},
  'space': {'id': '90121722741'},
  'attachments': [{'id': '02d3fd31-934c-4d69-a621-071e1d830086.pdf',
    'date': '1770476752134',
    'title': 'Parsons Nose (Putney) Invoice 07-Feb-26.pdf',
    'type': 2,
    'source': 1,
    'version': 0,
    'extension': 'pdf',
    'thumbnail_small': None,
    'thumbnail_medium': None,
    'thumbnail_large': None,
    'is_folder': None,
    'mimetype': 'application/pdf',
    'hidden': False,
    'parent_id': '90120190962480',
    'size': 61678,
    'total_comments': 0,
    'resolved_comments': 0,
    'user': {'id': 80488867,
     'username': 'Nicole',
     'email': 'msnicolebaro@gmail.com',
     'initials': 'N',
     'color': '',
     'profilePicture': 'https://attachments.clickup.com/profilePictures/80488867_lun.jpg'},
    'deleted': False,
    'orientation': None,
    'url': 'https://t9012223014.p.clickup-attachments.com/t9012223014/02d3fd31-934c-4d69-a621-071e1d830086/Parsons%20Nose%20(Putney)%20Invoice%2007-Feb-26.pdf',
    'email_data': None,
    'workspace_id': None,
    'url_w_query': 'https://t9012223014.p.clickup-attachments.com/t9012223014/02d3fd31-934c-4d69-a621-071e1d830086/Parsons%20Nose%20(Putney)%20Invoice%2007-Feb-26.pdf?view=open',
    'url_w_host': 'https://t9012223014.p.clickup-attachments.com/t9012223014/02d3fd31-934c-4d69-a621-071e1d830086/Parsons%20Nose%20(Putney)%20Invoice%2007-Feb-26.pdf?host=prod&ngsw-bypass=true'},
   {'id': 'c8447a71-e69d-48f4-b878-7ce0a594af86.mov',
    'date': '1770315259669',
    'title': 'image_picker_B538858F-794F-4F59-BCB8-B0CC66F846E2-409-0000008C429E71C33BE29191-A506-4D88-8214-3A7A8CA5B4D0.mov',
    'type': 1,
    'source': 1,
    'version': 0,
    'extension': 'mov',
    'thumbnail_small': None,
    'thumbnail_medium': None,
    'thumbnail_large': None,
    'is_folder': None,
    'mimetype': 'video/quicktime',
    'hidden': False,
    'parent_id': '869c1tu79',
    'size': 85435574,
    'total_comments': 0,
    'resolved_comments': 0,
    'user': {'id': 152482999,
     'username': 'Dardan Krasniqi ',
     'email': 'contact@besaconstruction.co.uk',
     'initials': 'DK',
     'color': None,
     'profilePicture': None},
    'deleted': False,
    'orientation': None,
    'url': 'https://t9012223014.p.clickup-attachments.com/t9012223014/c8447a71-e69d-48f4-b878-7ce0a594af86/image_picker_B538858F-794F-4F59-BCB8-B0CC66F846E2-409-0000008C429E71C33BE29191-A506-4D88-8214-3A7A8CA5B4D0.mov',
    'email_data': None,
    'workspace_id': None,
    'url_w_query': 'https://t9012223014.p.clickup-attachments.com/t9012223014/c8447a71-e69d-48f4-b878-7ce0a594af86/image_picker_B538858F-794F-4F59-BCB8-B0CC66F846E2-409-0000008C429E71C33BE29191-A506-4D88-8214-3A7A8CA5B4D0.mov?view=open',
    'url_w_host': 'https://t9012223014.p.clickup-attachments.com/t9012223014/c8447a71-e69d-48f4-b878-7ce0a594af86/image_picker_B538858F-794F-4F59-BCB8-B0CC66F846E2-409-0000008C429E71C33BE29191-A506-4D88-8214-3A7A8CA5B4D0.mov'},
   {'id': '91839b00-ed55-47a0-ad3b-418890537851.jpg',
    'date': '1770311879649',
    'title': '23ef008906521f5d042052d8f1702f71_exif.jpg',
    'type': 1,
    'source': 1,
    'version': 0,
    'extension': 'jpg',
    'thumbnail_small': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851_small.jpg',
    'thumbnail_medium': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851_medium.jpg',
    'thumbnail_large': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851_large.jpg',
    'is_folder': None,
    'mimetype': 'image/jpeg',
    'hidden': False,
    'parent_id': '869c1tu79',
    'size': 5374105,
    'total_comments': 1,
    'resolved_comments': 0,
    'user': {'id': 152482999,
     'username': 'Dardan Krasniqi ',
     'email': 'contact@besaconstruction.co.uk',
     'initials': 'DK',
     'color': None,
     'profilePicture': None},
    'deleted': False,
    'orientation': '1',
    'url': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851/23ef008906521f5d042052d8f1702f71_exif.jpg',
    'email_data': None,
    'workspace_id': None,
    'url_w_query': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851/23ef008906521f5d042052d8f1702f71_exif.jpg?view=open',
    'url_w_host': 'https://t9012223014.p.clickup-attachments.com/t9012223014/91839b00-ed55-47a0-ad3b-418890537851/23ef008906521f5d042052d8f1702f71_exif.jpg'},
   {'id': '35b0fe9a-936a-4f8d-815a-85eb66f7be80.jpg',
    'date': '1770311867686',
    'title': 'image_picker_6552CEBE-0961-4DA4-8AF8-9E514D1D4248-409-0000008C36979950.jpg',
    'type': 1,
    'source': 1,
    'version': 0,
    'extension': 'jpg',
    'thumbnail_small': 'https://t9012223014.p.clickup-attachments.com/t9012223014/35b0fe9a-936a-4f8d-815a-85eb66f7be80_small.jpg',

## Helpers

In [18]:
import re
import pandas as pd
import datetime
from extract import get_task_texts, labor_text_to_table
# ----------------------
# Helpers
# ----------------------
def get_custom_field_value(custom_fields, field_name):
    for field in custom_fields:
        if field.get("name") == field_name:
            return field.get("value")
    return None

def get_custom_field_option_name(custom_fields, field_name):
    for field in custom_fields:
        if field.get("name") == field_name and "value" in field:
            value = field["value"]
            for option in field.get("type_config", {}).get("options", []):
                if option.get("orderindex") == value:
                    return option["name"]
    return None

def safe_timestamp_to_date(ts):
    if ts:
        return datetime.datetime.fromtimestamp(int(ts) / 1000).strftime('%Y-%m-%d')
    return None

## Projects

In [19]:
# ----------------------
# Projects Table
# ----------------------
def build_projects_table(tasks):
    data = []
    for task in tasks:
        cf = task.get("custom_fields", [])
        row = {
            "project_id": task.get("id"),
            "client_name": get_custom_field_value(cf, "Client Name"),
            "sales_channel": get_custom_field_option_name(cf, "How did you hear about us?"),
            "project_name": task.get("name"),
            "client_address": get_custom_field_value(cf, "Project Address"),
            "client_email_address": get_custom_field_value(cf, "Email Address"),
            "client_phone_number": get_custom_field_value(cf, "Phone Number"),
            "project_status": task.get("status", {}).get("status"),
            "project_start_date": safe_timestamp_to_date(task.get("start_date")),
            "project_end_date": safe_timestamp_to_date(task.get("due_date")),
            "project_value": get_custom_field_value(cf, "Total Price (excl. VAT%)"),
            "dardan_days_worked": get_custom_field_value(cf, "01 Dardan (days worked)"),
            "musa_days_worked": get_custom_field_value(cf, "02 Musa (days worked)"),
            "dori_days_worked": get_custom_field_value(cf, "03 Dori (days worked)"),
            "remzi_days_worked": get_custom_field_value(cf, "04 Remzi (days worked)"),
        }
        data.append(row)

    projects_df = pd.DataFrame(data)
    return projects_df

raw_project_df = build_projects_table(detailed_tasks)

## Clean Projects

In [20]:
# ----------------------
# Cleaning Projects Table
# ----------------------

def clean_project_addresses(df):
    # Flexible UK postcode regex
    postcode_regex = r'([A-Z]{1,2}\d{1,2}[A-Z]?\s*\d[A-Z]{2})'
    
    def extract_parts(address):
        if not isinstance(address, str):
            return None, None, None, None, None
        
        # Normalize spaces & uppercase
        addr = re.sub(r'\s+', ' ', address.strip()).upper()
        
        # Find postcode
        m = re.search(postcode_regex, addr, re.IGNORECASE)
        if not m:
            return addr, None, None, None, None
        
        postcode = m.group(1).strip()
        
        # Split outward & inward
        m2 = re.match(r'([A-Z]{1,2}\d{1,2}[A-Z]?)\s*(\d[A-Z]{2})', postcode)
        outward = m2.group(1).upper() if m2 else None
        inward = m2.group(2).upper() if m2 else None
        
        # Break address into parts
        before_postcode = addr[:m.start()].strip(" ,")
        after_postcode = addr[m.end():].strip(" ,")

        city = None
        street = before_postcode
        
        # Case 1: city is before postcode (look for last comma section)
        if ',' in before_postcode:
            tokens = [t.strip() for t in before_postcode.split(',')]
            street = ', '.join(tokens[:-1])
            city = tokens[-1]
        
        # Case 2: city is after postcode
        if after_postcode:
            city = after_postcode
        
        return street, postcode, outward, inward, city, addr
    
    
    parts = df['client_address'].apply(lambda x: pd.Series(extract_parts(x)))
    parts.columns = ['client_street_name', 
                     'client_post_code', 
                     'client_outward_code', 
                     'client_inward_code', 
                     'client_city',
                     'client_address']
    
    return pd.concat([df.drop(columns=[
        "client_street_name", 
        "client_post_code", 
        "client_outward_code", 
        "client_inward_code", 
        "client_city", 
        "client_address"
    ], errors="ignore"), parts], axis=1)

cln_project_df = clean_project_addresses(raw_project_df)

## Materials

In [21]:
# ----------------------
# Materials Table
# ----------------------
def build_materials_table(tasks):
    material_data = []
    for task in tasks:
        project_id = task.get("id")
        project_name = task.get("name")
        for checklist in task.get("checklists", []):
            for item in checklist.get("items", []):
                raw_name = item.get("name", "").strip()
                match_full = re.match(r"^(.*?)[\s\-]+(\d+(?:\.\d+)?)[\s\-]+(\d+)$", raw_name)
                match_cost_only = re.match(r"^(.*?)[\s\-]+(\d+(?:\.\d+)?)$", raw_name)

                if match_full:
                    expense_name, expense_cost, quantity = match_full.group(1).strip(), float(match_full.group(2)), int(match_full.group(3))
                elif match_cost_only:
                    expense_name, expense_cost, quantity = match_cost_only.group(1).strip(), float(match_cost_only.group(2)), 1
                else:
                    expense_name, expense_cost, quantity = raw_name, None, None

                material_data.append({
                    "project_id": project_id,
                    "project_name": project_name,
                    "expense_name": expense_name,
                    "expense_cost": expense_cost,
                    "quantity": quantity
                })

    material_df = pd.DataFrame(material_data)
    return material_df

material_df = build_materials_table(detailed_tasks)
material_df

,project_id,project_name,expense_name,expense_cost,quantity
0,869c1tu79,PARSONS NOSE (Putney) #246,hps boiler,312.72,1.0
1,869c1tu79,PARSONS NOSE (Putney) #246,travis perkings,12.92,1.0
2,869bzfqnd,"SIGNE ,RUBER ROFF",raven ruber,480.95,1.0
3,869bzfqnd,"SIGNE ,RUBER ROFF",lords ply,31.44,1.0
4,869bzfqnd,"SIGNE ,RUBER ROFF",zyber proteck,15.39,1.0
...,...,...,...,...,...
278,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,metal frame steel,84.19,1.0
279,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,tools,9.88,1.0
280,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,materials,70.50,1.0
281,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,Floor Protection Materials,35.00,1.0
282,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,Paint Sandtex,47.00,1.0

## Services

In [22]:
def build_services_table(tasks):
    # ✅ filter projects with paid invoice status
    paid_projects = [
        t for t in tasks 
        if t.get("status", {}).get("status", "").lower() == "paid invoice"
    ]

    # map only paid projects
    task_id_to_name = {task["id"]: task["name"] for task in paid_projects}
    paid_project_ids = set(task_id_to_name.keys())

    subtasks = get_subtasks(BESA_CLIENTS_LIST_ID)
    subtasks_data = []

    for subtask in subtasks:
        parent_id = subtask.get("parent")

        # ✅ only keep subtasks whose parent is a paid project
        if parent_id in paid_project_ids:
            cf = subtask.get("custom_fields", [])
            project_name = task_id_to_name.get(parent_id)

            subtasks_data.append({
                "project_id": parent_id,
                "project_name": project_name,
                "project_status": "paid invoice",  # since we already filtered
                "subtask_id": subtask["id"],
                "subtask_name": subtask["name"],
                "service_price": get_custom_field_value(cf, "Total Price (excl. VAT%)"),
                "service_description": get_custom_field_value(cf, "Service Description"),
            })

    subtasks_df = pd.DataFrame(subtasks_data)
    return subtasks_df

build_services_table(detailed_tasks)

,project_id,project_name,project_status,subtask_id,subtask_name,service_price,service_description
0,869b7au2n,SIGNE. 69 RUSHMOLE ROAD #229,paid invoice,869brtmqz,top flore roof,530,None
1,869b7au2n,SIGNE. 69 RUSHMOLE ROAD #229,paid invoice,869brtmp4,deking,None,None
2,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq8tf,Living room door Relocated,280,None
3,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq3au,Storage unit doors 2 number,380,None
4,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq1mw,Front door paint,480,None
5,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpzt,paint laundry room,750,None
6,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpx2,garage door from out site paint,680,None
7,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpuu,kichen handels,320,None
8,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhptv,pipe draning block,365,None
9,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhprh,loft bords,530,None
10,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpqm,drowers shoe,680,None
11,869ax8dqh,KATE (35 Cloncurry Street) #220,paid invoice,869b13vmd,plumbfix material -9.26,None,None
12,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869b13tz8,roof painting,528,None
13,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kn5q,replase gatering,None,None
14,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kn1v,rendering back house,None,None
15,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kmvn,"painting - front ,side ,back house",None,None
16,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869b0kj3x,gutering,None,None
17,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869avrv4j,woodfloring in diner and kitchen,None,None
18,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869avrv07,rendering wall outsite,None,None

In [23]:
def build_services_table(tasks, status="paid invoice"):
    # ✅ filter projects by given status
    filtered_projects = [
        t for t in tasks 
        if t.get("status", {}).get("status", "").lower() == status.lower()
    ]

    # map project id → (name, status)
    task_id_to_meta = {
        task["id"]: {
            "name": task["name"],
            "status": task.get("status", {}).get("status", "")
        }
        for task in filtered_projects
    }
    project_ids = set(task_id_to_meta.keys())

    subtasks = get_subtasks(BESA_CLIENTS_LIST_ID)
    subtasks_data = []

    for subtask in subtasks:
        parent_id = subtask.get("parent")

        if parent_id in project_ids:
            cf = subtask.get("custom_fields", [])
            parent_meta = task_id_to_meta[parent_id]

            subtasks_data.append({
                "project_id": parent_id,
                "project_name": parent_meta["name"],
                "project_status": parent_meta["status"],     # 👈 project status
                "subtask_id": subtask["id"],
                "subtask_name": subtask["name"],
                "subtask_status": subtask.get("status", {}).get("status", ""),  # 👈 subtask status
                "service_price": get_custom_field_value(cf, "Total Price (excl. VAT%)"),
                "service_description": get_custom_field_value(cf, "Service Description"),
            })

    subtasks_df = pd.DataFrame(subtasks_data)
    return subtasks_df

build_services_table(detailed_tasks)

,project_id,project_name,project_status,subtask_id,subtask_name,subtask_status,service_price,service_description
0,869b7au2n,SIGNE. 69 RUSHMOLE ROAD #229,paid invoice,869brtmqz,top flore roof,warm lead,530,None
1,869b7au2n,SIGNE. 69 RUSHMOLE ROAD #229,paid invoice,869brtmp4,deking,warm lead,None,None
2,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq8tf,Living room door Relocated,warm lead,280,None
3,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq3au,Storage unit doors 2 number,warm lead,380,None
4,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bgq1mw,Front door paint,warm lead,480,None
5,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpzt,paint laundry room,warm lead,750,None
6,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpx2,garage door from out site paint,warm lead,680,None
7,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpuu,kichen handels,warm lead,320,None
8,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhptv,pipe draning block,warm lead,365,None
9,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhprh,loft bords,warm lead,530,None
10,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,paid invoice,869bdhpqm,drowers shoe,warm lead,680,None
11,869ax8dqh,KATE (35 Cloncurry Street) #220,paid invoice,869b13vmd,plumbfix material -9.26,warm lead,None,None
12,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869b13tz8,roof painting,warm lead,528,None
13,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kn5q,replase gatering,warm lead,None,None
14,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kn1v,rendering back house,warm lead,None,None
15,869azy4ex,KATE SANFORD (58 St James’s Road) #224,paid invoice,869b0kmvn,"painting - front ,side ,back house",warm lead,None,None
16,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869b0kj3x,gutering,warm lead,None,None
17,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869avrv4j,woodfloring in diner and kitchen,warm lead,None,None
18,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,paid invoice,869avrv07,rendering wall outsite,warm lead,None,None

In [24]:
# ----------------------
# Services Table
# ----------------------
def build_services_table(tasks):
    subtasks = get_subtasks(BESA_CLIENTS_LIST_ID)
    task_id_to_name = {task["id"]: task["name"] for task in detailed_tasks}
    subtasks_data = []
    for subtask in subtasks:
            if subtask.get("parent"):
                    cf = subtask.get("custom_fields",[])
                    parent_id = subtask['parent']
                    project_name = task_id_to_name.get(parent_id)
            subtasks_data.append({
                    "project_id": parent_id,
                    "project_name": project_name,
                    "project_status": task["status"],
                    "subtask_id": subtask["id"],
                    "subtask_name": subtask['name'],
                    "service_price": get_custom_field_value(cf,'Total Price (excl. VAT%)'),
                    "service_description": get_custom_field_value(cf,'Service Description')
            })
            subtasks_df = pd.DataFrame(subtasks_data)
    subtasks_df = pd.DataFrame(subtasks_data)
    return subtasks_df

build_services_table(detailed_tasks)

,project_id,project_name,project_status,subtask_id,subtask_name,service_price,service_description
0,869c593gv,None,"{'status': 'no response/refusal', 'id': 'sc901...",869c596p1,Send a kind introductory email,None,None
1,869c3y2xp,None,"{'status': 'no response/refusal', 'id': 'sc901...",869c3y3ty,Jet wash the deck,None,None
2,869c1mc94,None,"{'status': 'no response/refusal', 'id': 'sc901...",869c3y3kz,Spiral staircase to roof decking:,None,None
3,869c1mc94,None,"{'status': 'no response/refusal', 'id': 'sc901...",869c3y3f8,Paint in the front house,None,None
4,869c1mc94,None,"{'status': 'no response/refusal', 'id': 'sc901...",869c3y2xp,Opening wall between the kitchen and the dini...,None,None
...,...,...,...,...,...,...,...
57,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,"{'status': 'no response/refusal', 'id': 'sc901...",869avrv07,rendering wall outsite,None,None
58,869atzef7,None,"{'status': 'no response/refusal', 'id': 'sc901...",869atzegj,Service 4 - Biding,80,None
59,869atzef7,None,"{'status': 'no response/refusal', 'id': 'sc901...",869atzegh,"Service 5 - Supply, build and paint custom sho...",320,None
60,869atzef7,None,"{'status': 'no response/refusal', 'id': 'sc901...",869atzege,Service 3 - Tiles Extension,120,None
61,869atzef7,None,"{'status': 'no response/refusal', 'id': 'sc901...",869atzegc,picher paneling,None,None

## Labor

In [ ]:
# ----------------------
# Labor Table
# ----------------------
def build_labor_table(tasks, existing_df=None):
    """
    Loops through all tasks and combines their labor logs into one DataFrame.
    Keeps existing labor data (if provided) and appends new tasks.
    
    Parameters:
        tasks (list): List of task dictionaries
        existing_df (pd.DataFrame, optional): Existing labor table to keep
    
    Returns:
        pd.DataFrame: Updated labor table sorted by Date
    """
    task_texts = get_task_texts(tasks) 
    all_labor = []

    # Keep existing data if provided
    if existing_df is not None:
        all_labor.append(existing_df)
        existing_task_ids = set(existing_df['project_id'].unique())
    else:
        existing_task_ids = set()

    for task_id, text in task_texts.items():
        # Only process tasks that are not already in existing_df
        if task_id not in existing_task_ids and text.strip():  
            df = labor_text_to_table(text, task_id) 
            if not df.empty: 
                all_labor.append(df)

    if all_labor: 
        labor_df = pd.concat(all_labor, ignore_index=True)

        # Convert 'Date' to datetime and sort chronologically
        labor_df['Date'] = pd.to_datetime(labor_df['Date'], format='%d.%m.%y')
        labor_df = labor_df.sort_values('Date').reset_index(drop=True)

        return labor_df

    return existing_df if existing_df is not None else pd.DataFrame()

labor_df = build_labor_table(ongoing_tasks)
labor_df

^^ This didn't work

## CLEANING - Normalise tables into 3rd Normal Form

#### Client Dimension

In [28]:
# --- Client Dimension ---
client_dim = cln_project_df[["client_name",
                        "sales_channel",
                        "client_email_address",
                        "client_phone_number",
                        "client_street_name",
                        "client_post_code",
                        "client_outward_code",
                        "client_inward_code",
                        "client_city"]]
client_dim = client_dim.drop_duplicates(
    subset=["client_name", "client_email_address", "client_post_code"],
    keep="first"
).reset_index(drop=True)
client_dim['client_numeric_id'] = client_dim.index + 1
client_dim['client_id'] = client_dim['client_numeric_id'].apply(lambda x: f"C{x:03d}")  # e.g., C001
client_dim.drop(['client_numeric_id'],axis=1,inplace=True)
client_dim.dropna(axis=0, how="all",inplace=True)

In [29]:
client_dim

,client_name,sales_channel,client_email_address,client_phone_number,client_street_name,client_post_code,client_outward_code,client_inward_code,client_city,client_id
0,None,None,None,None,None,None,None,None,None,C001
1,Axel Mathysen Gerst,None,Axelamg@hotmail.com,None,7A SCHUBERT ROAD,SW15 2QT,SW15,2QT,LONDON,C002
2,ELAINE KLANDER,From a Friend,Elaine@klander.com,+44 7957 165393,36 SCHOOL ROAD EAST MOLESEY,KT8 0DN,KT8,0DN,None,C003
3,TONI Hindhaugh,Existing Client,catherine@parsonsnose.co.uk,None,753 FULHAM ROAD,SW6 5UU,SW6,5UU,LONDON,C004
4,None,None,tpk@colesbourne.com,+44 7801 430020,103 NEW KINS ROAD,None,None,None,None,C005
5,VICTORIA NGUYEN,None,victoriakieuanhnguyen@gmail.com,+44 7909 785501,60 EATONS MEWS NORTH,SW1X 8LL,SW1X,8LL,None,C006
6,MATTHEW ROYLE,Existing Client,Oxberryfulham@gmail.com,None,11 CHEPSTOW CLOSE,SW15 2HG,SW15,2HG,PUTNEY,C007
7,IMOGEN,None,imogen.watson@btopenworld.com,+44 7766 857638,10A LOUVAINE ROAD,SW11 2AQ,SW11,2AQ,None,C008
8,KATY,Existing Client,info@katyellisinteriordesign.com,+447896946015,3 RUSHHILL MEWS,SW11 5NB,SW11,5NB,None,C009
9,ANNA ( JAN ),Existing Client,Acpare@gmail.com,+44 7802 980660,45 CALDERVALE ROAD,SW8 9LY,SW8,9LY,LONDON,C010
10,JAQUELINE TUCKER,Existing Client,Jaqueline.tucker@yahoo.com,+44 7866 101438,25 ELSYNGE ROAD,SW18 2HR,SW18,2HR,None,C011
11,Signe Hammond,Existing Client,signehammond@gmail.com,None,69 RUSHMOLE ROAD,SW15 3LF,SW15,3LF,LONDON,C012
12,NICKY,Existing Client,nickyfry@klander.com,+44 7780 224069,FLAT 2 61 - 69 CHEPSTOW PLACE LONDON,W2 4TS,W2,4TS,None,C013
13,TANIA HAMILTON,Word Of Mouth,t@tania.style,+44 7770 963366,14 BURLINGTON ROAD,SW6 4NR,SW6,4NR,FULHAM,C014
14,CATHERINA SANFORD,Word Of Mouth,terrykatesanford@yahoo.co.uk,+44 7926 979669,None,None,None,None,None,C015
15,kate,Existing Client,None,+44 7779 728288,35 CLONCURRY STREET,None,None,None,None,C016
16,JANE HARROP,Client Neighbour,None,+44 7771 985227,11 RODWAY ROAD,SM15 5DN,SM15,5DN,None,C017
17,TAUSIF,None,Awan.tausif@gmail.com,+44 7435 977656,304 MALDEN ROAD,KT3 6AT,KT3,6AT,None,C018
18,PETER,From a Friend,PETER_CLUSKYA@yahoo.co.uk,+44 7735 402565,57 QUEENS DRIVE SURBITON,KT5 8PW,KT5,8PW,None,C019
19,Damian Adamski,Existing Client,damianadamski.uk@gmail.com,None,None,None,None,None,None,C020
20,Gorge,Existing Client,armando.kita@albrit.co.uk,None,15 BEDFORD ROAD,None,None,None,None,C021
21,TONY HINDHAUGH,Existing Client,tony@parsonsnose.co.uk,+44 7717 750885,"FULHAM ,KINSINTON , BELGREVIA . SHOPS",None,None,None,None,C022
22,LOTTIE DUNNE,Existing Client,lottie.dunne@hotmail.com,+44 7875 413584,8 DONERAILE STREET,SW6 6EN,SW6,6EN,None,C023
23,SIVAN EINSTEIN,Existing Client,einstein.sivan@gmail.com,+447922916745,80 FITZJOHN'S AVENUE,NW3 5LS,NW3,5LS,FLAT 6,C024
24,Diana Fleming,From a Friend,flemingdiana@hotmail.com,+447712594730,23 CLONCURRY STREET,SW6 6DR,SW6,6DR,LONDON,C025
25,GEORGE FLAT,None,None,None,19 SILCHESTER ROOD,W10 6SF,W10,6SF,None,C026
26,Francesca Philips,Existing Client,francesca@francescaphillips.com,+34 687 86 65 24,46 HORTON STREET,W8 4NT,W8,4NT,LONDON,C027
27,Martin Browne,Existing Client,martinbrowne17@gmail.com,+44 7462 336832,46 WATERFORD ROAD,SW6 2DR,SW6,2DR,LONDON,C028
28,GEORGE CLARKE,From a Friend,None,None,15 BEDFORD ROAD,W4 1JD,W4,1JD,None,C029
29,SIMON ROBBIE,Existing Client,simon.j.robbie@gmail.com,+44 7767 080400,98 SUGDEN ROAD,SW11 5EE,SW11,5EE,None,C030
30,Kilfree Ltd,Existing Client,david@kilfreeltd.co.uk,+44 7716 797405,15 DEANS ROAD,W7 3QD,W7,3QD,HANWELL,C031
31,laura,Word Of Mouth,Laurajavid@gmail.com,+447545380968,40 STOKENCHURCH STREET,SW6 4SJ,SW6,4SJ,LONDON,C032
32,Toni Hindhaugh,Word Of Mouth,catherine@parsonsnose.co.uk,+44 7717 750885,81 EBURY STREET,SW1W 9NP,SW1W,9NP,BELGRAVIA,C033
33,PETER SINCLAIR,Existing Client,peter.sinclair3@ntlworld.com,+447921589647,14 ROYSTON COURT HOOK RISE NORTH SURBITON,KT6 7JX,KT6,7JX,None,C034
34,Anna,Existing Client,Acpare@gmail.com,+44 7802 980660,45 CALDERVALE ROAD,SW8 9LY,SW8,9LY,LONDON,C035
35,Kate Bartlett,None,katebartlett81@gmail.com,None,35 CLONCURRY STREET,SW6 6DR,SW6,6DR,LONDON,C036
36,tony hindhaugh,Existing Client,tony@parsonsnose.co.uk,+44 7717 750885,"ULLAPOOL, SCOTLAND",None,None,None,None,C037
37,Tom King,Existing Client,tpk@colesbourne.com,+44 7801 430020,22 ANSTIS STREET,PL15JT,PL1,5JT,PLYMOUTH,C038
38,Kendall Bailey,Existing Client,kendall.fitch@gmail.com,+1 404 345 7206,12 DONARELLE STREET,SW6 6EL,SW6,6EL,FULHAM,C039
39,Francesca Phillips,Existing Client,francesca@francescaphillips.com,+34 687 86 65 24,46 HORNTON STREET,W8 4NT,W8,4NT,LONDON,C040
40,Rebecca Harper,Word Of Mouth,Rebecca.c.james@hotmail.co.uk,None,13 RODWAY ROAD,SW15 5DN,SW15,5DN,LONDON,C041
41,Toni Hindhaugh,Word Of Mouth,serena@parsonsnose.co.uk,+44 7717 750885,81 EBURY STREET,SW1W 9NP,SW1W,9NP,BELGRAVIA,C042
42,Toni Hindhaugh,Word Of Mouth,catherine@parsonsnose.co.uk,+44 7717 750885,5 HEATHMANS ROAD,SW6 4TJ,SW6,4TJ,FULHAM,C043
43,Shabhan,Word Of Mouth,shaban@vitalbs.co.uk,None,36 KERSLEY STREET,SW11 4PT,SW11,4PT,LONDON,C044
44,Kate Bartlett,Word Of Mouth,katebartlett81@gmail.com,None,35 CLONCURRY STREET,SW66DR,SW6,6DR,LONDON,C045
45,Lottie Dunne,Word Of Mouth,lottie.dunne@hotmail.com,+44 7875 413584,8 DONERAILE STREET,SW6 6EN,SW6,6EN,LONDON,C046
46,Siobhan Mulholland,Word Of Mouth,Mulholland@ndo.co.uk,+44 7788 597402,33 CLONCURRY STREET,SW66DR,SW6,6DR,LONDON,C047

Connect to BigQuery

In [30]:
from google.cloud import bigquery

client = bigquery.Client(project="besa-construction-database")
sql = "SELECT * FROM `clean_dataset.ClientDim` LIMIT 10"
df = client.query(sql).to_dataframe()
print(df.head())

/Users/madalinasamoila/besa_pipeline/.venv/lib/python3.13/site-packages/google/cloud/bigquery/table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

  string_field_0  string_field_1   string_field_2          string_field_3  \
0           C025            None             None                    None
1           C009  tony hindhaugh  Existing Client  tony@parsonsnose.co.uk
2           C032  James Sinclair  Existing Client        jimsin12@aol.com
3           C010       Tom King   Existing Client     tpk@colesbourne.com
4           C017         Shabhan    Word Of Mouth    shaban@vitalbs.co.uk

    string_field_4                                     string_field_5  \
0             None                                               None
1  +44 7717 750885                                               None
2             None  14 ROYSTON COURT HOOK RISE, NORTH SURBITON, KT...
3  +44 7801 430020                 22 ANSTIS STREET, PLYMOUTH, PL15JT
4             None                36 KERSLEY STREET, LONDON, SW11 4PT

               string_field_6 string_field_7 string_field_8 string_field_9  \
0                        None           None           None           None
1                        None           None           None           None
2  14 ROYSTON COURT HOOK RISE        KT6 7JX            KT6            7JX
3            22 ANSTIS STREET         PL15JT            PL1            5JT
4           36 KERSLEY STREET       SW11 4PT           SW11            4PT

  string_field_10
0            None
1            None
2  NORTH SURBITON
3        PLYMOUTH
4          LONDON

In [ ]:
import os

cur_path = os.getcwd()
file ='ProjectDim.csv'
file_path = os.path.join(cur_path,"data/clean",file)
print(file_path)

/Users/madalinasamoila/besa_pipeline/data/clean/ProjectDim.csv

### LoadJobConfig

https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfigurationLoad.FIELDS.write_disposition

In [31]:
# modules
from google.cloud import bigquery
import os

# Instantiate our client 
# Define where our data should be loaded to (in this case google cloud -> besa-construction -> clean_dataset -> ProjectDim)
client = bigquery.Client(project="besa-construction-database")
target_table = "besa-construction-database.clean_dataset.ProjectDim"

# Defining the Job Config for how the data should be inserted
job_config = bigquery.LoadJobConfig(
    skip_leading_rows=1,
    source_format=bigquery.SourceFormat.CSV,
    autodetect= True,
    write_disposition='WRITE_TRUNCATE'
)

# Set the path to the file
cur_path = os.getcwd()
file ='ProjectDim.csv'
file_path = os.path.join(cur_path,"data/clean",file)
print(file_path)

# Open the file, add parameters
with open(file_path,'rb') as source_file:
    load_job = client.load_table_from_file(
        source_file,
        target_table,
        job_config=job_config
    )

load_job.result()

destination_table = client.get_table(target_table)
print(f"You have {destination_table.num_rows} rows in your table")

/Users/madalinasamoila/besa_pipeline/data/clean/ProjectDim.csv
You have 62 rows in your table

### Load all the rest of the CSV files

In [32]:
# modules
from google.cloud import bigquery
import os

# Instantiate our client 
# Define where our data should be loaded to (in this case google cloud -> besa-construction -> clean_dataset -> ProjectDim)
client = bigquery.Client(project="besa-construction-database")

# List of CSV files and thier corresponding target tables
csv_table_mapping = {
    "ClientDim.csv": "besa-construction-database.clean_dataset.ClientDim",
    "ProjectDim.csv": "besa-construction-database.clean_dataset.ProjectDim",
    "ExpenseFact.csv": "besa-construction-database.clean_dataset.ExpenseFact",
    "ProjectFact.csv": "besa-construction-database.clean_dataset.ProjectFact"
}

# Defining the Job Config for how the data should be inserted
job_config = bigquery.LoadJobConfig(
    skip_leading_rows=1,
    source_format=bigquery.SourceFormat.CSV,
    autodetect= True,
    write_disposition='WRITE_TRUNCATE'
)

# Loop through each file and load it into BigQuery


cur_path = os.getcwd()
file ='ProjectDim.csv'
file_path = os.path.join(cur_path,"data/clean",file)
print(file_path)

# Open the file, add parameters
with open(file_path,'rb') as source_file:
    load_job = client.load_table_from_file(
        source_file,
        target_table,
        job_config=job_config
    )

load_job.result()

destination_table = client.get_table(target_table)
print(f"You have {destination_table.num_rows} rows in your table")

/Users/madalinasamoila/besa_pipeline/data/clean/ProjectDim.csv
You have 62 rows in your table

In [33]:
for file_name, target_table in csv_table_mapping.items():
    file_path = os.path.join(cur_path,"data/clean",file_name)
    print(f"Loading {file_path} into {target_table}...")

    with open(file_path,'rb') as source_file:
        load_job = client.load_table_from_file(
        source_file,
        target_table,
        job_config=job_config
    )

    load_job.result()

    destination_table = client.get_table(target_table)
    print(f"You have {destination_table.num_rows} rows in your {target_table} table")

Loading /Users/madalinasamoila/besa_pipeline/data/clean/ClientDim.csv into besa-construction-database.clean_dataset.ClientDim...
You have 32 rows in your besa-construction-database.clean_dataset.ClientDim table
Loading /Users/madalinasamoila/besa_pipeline/data/clean/ProjectDim.csv into besa-construction-database.clean_dataset.ProjectDim...
You have 62 rows in your besa-construction-database.clean_dataset.ProjectDim table
Loading /Users/madalinasamoila/besa_pipeline/data/clean/ExpenseFact.csv into besa-construction-database.clean_dataset.ExpenseFact...
You have 263 rows in your besa-construction-database.clean_dataset.ExpenseFact table
Loading /Users/madalinasamoila/besa_pipeline/data/clean/ProjectFact.csv into besa-construction-database.clean_dataset.ProjectFact...
You have 60 rows in your besa-construction-database.clean_dataset.ProjectFact table

In [34]:
destination_table = client.get_table(target_table)
destination_table

Table(TableReference(DatasetReference('besa-construction-database', 'clean_dataset'), 'ProjectFact'))

In [35]:
with open(file_path) as source_file:
    print(source_file.read())

project_id,project_name,project_value,dardan_days_worked,musa_days_worked,dori_days_worked,remzi_days_worked,total_material_cost
869a9uhvd,EXEL (7A SCHUBERT ROAD SW15 2QT) #210,3040,2,2,2,,192.21000000000004
869a9a7rn,FRANCESCA (46 HORNTON STREET ),180,0.2,0.2,0.2,,0.0
869a61xwk,MARTIN BROWNE (46 WATERFORD ROAD) #205,1420,0.5,0.5,0.5,,128.38
869a588v6,MARTIN (46 WATERFORD ROAD) #204,270,0.2,,0.2,,80.0
869a12e5z,DAVID (SUPPLY & INSTALL TIMBER STUD) 15 DEANS ROAD #143,4250,1,1,1,0,
8699zaq36,LAURA (40 STOKENCHURCH STREET) #202,2400,2,2,2,,202.48
8699w2nyd,PARSONS NOSE BELGRAVIA (FIX SINK & PIPE) 81 EBURY STREET  #200,350,1,0,0,0,
8699nmjq2,MARTIN 46 WATERFORD ROAD #198,1000,1,0,0,0,82.39999999999999
8699ftxm9,ANNA (PAINTING) 45 CALDERVALE ROAD #189,590,0.5,0,0,0.5,85.0
8699cky12,KATE 35 CLONCURRY STREET #300,2600,2,2,2,,378.4
86999z3pc,PARSONS NOSE SCOTLAND,11000,6,13,13,0,0.0
86999ywg8,TOM KING 103 NEW KINGS ROAD #194,5575,4,0,0,8,3111.93
86999yv2u,KENDALL (ONE DAY) 12 DONARELLE STREET #171,1000,0,0.5,0.5,0,91.08
869937qtr,FRANCESCA (BEDROOM & BASEMENT REPAIR) 46 HORNTON STREET #188,2100,2,2,2,0,546.04
8698za3ft,BECKS 13 RODWAY ROAD #187,4620,2,2,1,0,0.0
8698wc2m7,SIGNE (ROOF WATERPROOFING) 69 RUSHMOLE ROAD #185,6650,3,2,3,0,1301.7
8698uwr7k,PARSONS NOSE BELGRAVIA (SHOP RENOVATION) 81 EBURY STREET #184,19000,10,9,8,4,2439.0660000000003
8698tfzfu,PARSONS NOSE FULHAM (CEILING) 5 HEATHMANS ROAD #183,850,1,1,1,0,
8698nkayw,SHABHAN (LOFT PROJECT) 36 KERSLEY STREET,6000,14,14,13,0,4806.3
8698m1cnu,KATE (ROOFING) 35 CLONCURRY STREET #178,1600,1,1,1,0,486.31
8698kr47j,LOTTIE DUNNE (PAINT) 8 DONARELLE STREET #176,650,0,1,1,0,79.8
8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROAD #175,460,0.5,0.5,0.5,0,94.07
8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,660,1,1.5,1.5,0,152.5
8698h58rk,"CAROLE (EXTRA, 1 DAY BATHROOM) 33 CLONCURRY STREET #172",1100,0.5,2,0,0,1576.1399999999999
8698f2nhc,PARSONS NOSE FULHAM (WC) 5 HEATHMANS ROAD #161,195,0.5,0,0,0,22.87
8698b9jk5,SIOBHAN-KATE (WALL) 33 CLONCURRY STREET #169,2350,2.25,0.25,2.25,0,424.56
86988bbmc,PARSONS NOSE FULHAM (DRAINING) 5 HEATHMANS ROAD #164,580,1,1,1,0,50.0
869861eqe,CAROLE (BATHROOM RENOVATION) 29 CLONCURRY STREET #170,9960,10,10,10,0,1310.4299999999998
86983j99c,SOPHIE PAUL (PAINTING) 52 PURSERS CROSS RD #162,8257,5,1,1,5.5,2851.4
86983haa3,PARSONS NOSE HQ (SINK & DOOR HANDLE) 753 FULHAM ROAD #161,877.29,1,1,1,0,197.29
86982m2w0,"Mark 63 Eaton Mews North, SW1X 8LL",51225.6,,,,,
86981wgff,DAVID (WC) 15 DEANS ROAD #159,3100,3,3,3,0,
86981hvar,MATTHEW 15 OXBERRY AVE #160,6160,2,2,2,0,2651.12
8697w3zyx,PARSONS NOSE PUTNEY (FLOOR WORK) 88 LOWER RICHMOND ROAD #165,2466.96,2,2,2,0,616.96
8697vfd88,DAVID (BUILD WARDROBE) 15 DEANS ROAD #152,2850,4,2,5,0,599.71
8697ncwg3,PARSONS NOSE FULHAM (KITCHEN INSTALLATION) 5 HEATHMANS ROAD #151,3475.28,1,1,1,0,1763.3600000000001
8697ncvrx,DAVID (PAINT GROUND & FIRST FLOOR) 15 DEANS ROAD #153,3100,6,6,2,0,628.38
8697hqd6k,PARSONS NOSE FULHAM (DOOR SOFT CLOSER) 5 HEATHMANS ROAD #146,479.96,0,1,0,0,139.98
8697hqamt,PARSONS NOSE FULHAM (ELECTRIC FUSE BOARD DOOR) 5 HEATHMANS ROAD #145,250,0.5,0.5,0,0,
8697gxkhy,KATE (PAINT & REPAIR) 35 CLONCURRY STREET #158,2635,4,1,1,0,296.18
8697gepb2,PARSONS NOSE FULHAM (SINK & PATIO HEATER ) 5 HEATHMANS ROAD #144,710,1.5,0.5,0,0,120.84
8697genff,PARSONS NOSE HQ (FIRE PLASTER BOARD) 753 FULHAM ROAD #142,702.99,0.5,0.5,0.5,0,112.99
8697ge2ga,BEI LONDON (DOME ROOF LIGHTS) 703 FULHAM ROAD #141,600,1,0,0,0,
8697frptn,DAVID (PAINT 2 DOORS) 15 DEANS ROAD #152,650,0,0,1,0,79.78
8697freuy,DAVID (BATHROOM TILES) 15 DEANS ROAD #154,1850,1,1,7,0,163.49
8697frbur,DAVID (PAINT NEW STEPS & LOFT) 15 DEANS ROAD #152,2600,6,6,6,0,319.99999999999994
8697fracb,DAVID (PANELLING) 15 DEANS ROAD #146,2450,3,3,3,0,363.52
8697fr0kp,DAVID (PLASTER MULTIFINISH) 15 DEANS ROAD,1250,1,2,2,0,410.17
8697fqgm7,DAVID (WALLPAPER REMOVAL) 15 DEANS ROAD ,850,1,1,1,0,100.0
8697em86c,PARSONS NOSE KENSINGTON (LIGHTING REPLACE) 165 OLD BROMPTON ROAD #139,680,0.5,0.5,0.5,0,64.52
8697aqw30,LIZZIE (ELECTRICAL) 33 EPPLE ROAD #138,600,0,1,1,0,
8697aqu87,DAVID (WALL PANELLING) 15 DEANS ROAD #143,2100,1,1,1,0,1326.6
86976btp8,LIZZIE (BASEMENT) 33 EPPLE ROAD #131,2450,0,3,3,0,604.6500000000001
86976bnvg,LIZZIE (KITCHEN PAINTING) 33 EPPLE ROAD #132,1950,4,1,0,0,337.43
869768rvk,LIZZIE (WALL PANELLING) 33 EPPLE ROAD #137,2950,3,4,4,0,671.39
869768ng4,LIZZIE (PAINTING SITING ROOM) 33 EPPLE ROAD #130,950,1,2,2,0,295.0
86975hvrd,BEI LONDON (PAINT WALLS & CEILING) 703 FULHAM RD #309,5920,8,8,8,0,848.5600000000001
8696y7rez,LIZZIE (BEDROOM) 33 EPPLE ROAD #128,6362,8,8,9,0,1322.6799999999998
8696vzghe,PARSONS NOSE FULHAM (KITCHEN VENT PIPE) 5 HEATHMANS ROAD #123,950,1,1,1,0,259.13
8696tarzu,JAMES (CAT CAGE) 14 ROYSTON COURT #140,60,0.5,0,0,0,

#### Project Dimension

In [36]:
# --- Project Dimension ---
project_dim = cln_project_df[[
        "project_id", 
        "project_name", 
        "project_status",
        "project_start_date", 
        "project_end_date", 
        "client_name",
        "client_post_code"
]].merge(client_dim[["client_id","client_name","client_post_code"]], on=["client_name", "client_post_code"], how="left")

project_dim = project_dim.drop(columns=["client_name","client_post_code"])
project_dim

,project_id,project_name,project_status,project_start_date,project_end_date,client_id
0,869c1tu79,PARSONS NOSE (Putney) #246,paid invoice,None,None,C001
1,869c1tu79,PARSONS NOSE (Putney) #246,paid invoice,None,None,C005
2,869bzfqnd,"SIGNE ,RUBER ROFF",paid invoice,None,None,C001
3,869bzfqnd,"SIGNE ,RUBER ROFF",paid invoice,None,None,C005
4,869bwemyd,EXEL (7A SCHUBERT ROAD SW15 2QT) #239,paid invoice,None,None,C002
...,...,...,...,...,...,...
58,8698nkayw,SHABHAN (LOFT PROJECT) 36 KERSLEY STREET,paid invoice,2025-04-09,2025-05-04,C044
59,8698m1cnu,KATE (ROOFING) 35 CLONCURRY STREET #178,paid invoice,2025-04-08,2025-04-09,C045
60,8698kr47j,LOTTIE DUNNE (PAINT) 8 DONARELLE STREET #176,paid invoice,2025-04-05,2025-04-05,C046
61,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,paid invoice,2025-04-04,2025-04-04,C043
62,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,paid invoice,2025-04-04,2025-04-04,C047

#### Material Fact

In [37]:
# --- Material Fact ---
material_fact = material_df.rename(columns={
        "expense_name": "expense_name",
        "expense_cost": "expense_cost",
        "quantity": "quantity"
    })
[["project_id", "expense_name", "expense_cost", "quantity"]]
material_fact

,project_id,project_name,expense_name,expense_cost,quantity
0,869c1tu79,PARSONS NOSE (Putney) #246,hps boiler,312.72,1.0
1,869c1tu79,PARSONS NOSE (Putney) #246,travis perkings,12.92,1.0
2,869bzfqnd,"SIGNE ,RUBER ROFF",raven ruber,480.95,1.0
3,869bzfqnd,"SIGNE ,RUBER ROFF",lords ply,31.44,1.0
4,869bzfqnd,"SIGNE ,RUBER ROFF",zyber proteck,15.39,1.0
...,...,...,...,...,...
278,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,metal frame steel,84.19,1.0
279,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,tools,9.88,1.0
280,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,materials,70.50,1.0
281,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,Floor Protection Materials,35.00,1.0
282,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,Paint Sandtex,47.00,1.0

#### Project Fact

In [44]:
# --- Project Fact ---
# Aggregate materials to get total_material_cost
total_materials = (
        material_df.groupby("project_id")
        .apply(lambda x: (x["expense_cost"] * x["quantity"]).fillna(0).sum())
        .reset_index(name="total_material_cost")
    )
project_fact = cln_project_df[[
        "project_id", 
        "project_name",
        "project_value",
        "dardan_days_worked", 
        "musa_days_worked",
        "dori_days_worked", 
        "remzi_days_worked"
    ]].merge(total_materials, on="project_id", how="left")
project_fact

/var/folders/qv/dzzbgwwd3lx5227l6qt6cvmh0000gn/T/ipykernel_1725/3517528389.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: (x["expense_cost"] * x["quantity"]).fillna(0).sum())

,project_id,project_name,project_value,dardan_days_worked,musa_days_worked,dori_days_worked,remzi_days_worked,total_material_cost
0,869c1tu79,PARSONS NOSE (Putney) #246,662.72,0.5,None,0.5,None,325.640
1,869bzfqnd,"SIGNE ,RUBER ROFF",1860,1,1,1,1,527.780
2,869bwemyd,EXEL (7A SCHUBERT ROAD SW15 2QT) #239,350,None,None,None,None,25.780
3,869buyaht,ELAINE KLADER (36 School Road) #240,2450,2.5,2.5,2.5,None,367.800
4,869bu5vq4,parsons nose shops,1576,2,1.5,None,None,307.800
5,869brqjq1,TOM KING (103 NEW KINS ROAD) #236,707.39,1,1,None,None,257.390
6,869brqg9g,Victoria painting kichen,1200,2,2,None,None,231.710
7,869brqafr,MATTHEW ROYLE. CHEPSTOW CLOSE #235,2620,2,2,2,None,113.260
8,869bagzfk,IMOGEN - WALL (10A LOUVAINE ROAD ),1780,1,1,1,None,185.000
9,869b84yve,"KATY (3 Rushhill Mews, SW11 5NB)",None,None,None,None,None,136.150
10,869b7u4yp,ANNA,910,1,1,1,None,0.000
11,869b7tzjr,JAQUELINE TUCKER (25 ELSYNGE ROAD SW18 2HR) #228,None,None,None,None,None,NaN
12,869b7au2n,SIGNE. 69 RUSHMOLE ROAD #229,1367.5,1,2,2,None,190.420
13,869b602yc,NICKY 61 CHEPSTOW PLACE,690,None,None,None,None,232.800
14,869b5z5c9,TANIA HAMILTON (14 BURLINGTON ROAD) #230,1650,None,2,2,None,600.000
15,869b4bjd5,IMOGEN (10A LOUVAINE ROAD) #231,1780,None,None,None,None,NaN
16,869azy4ex,KATE SANFORD (58 St James’s Road) #224,None,5,5,5,None,1296.810
17,869ax8dqh,KATE (35 Cloncurry Street) #220,2640,1,1,1,None,370.100
18,869awpek5,JANE HARROP (11 RODWAY ROAD) #224,1220,1,1,None,None,209.290
19,869auttbk,TAUSIF AWAN (304 MALDEN ROAD KT3 6AT) #219,7480,None,None,None,None,NaN
20,869auc6kr,PETE (57 Queens DRIVE ),2410,3,3,3,None,394.700
21,869ar1ad8,AI AGENT (TEST-5),None,None,None,None,None,NaN
22,869ana4eq,GEORGE EXTRA WORK (15 BEDFORD ROAD) #218,3760,3,3,3,None,565.540
23,869am3vm7,PARSONS NOSE SHOPS,1135,1,1,1,None,180.490
24,869am3jx4,LOTTIE DUNNE (8 Doneraile STREET SW6 6EN) #216,None,0.5,0.5,0.5,None,NaN
25,869agkrhw,PARSONS NOSE FULHAM #214,890,1.2,1.2,0.2,None,168.470
26,869acw863,SIVAN (80 FITZJOHNS FLAT 6) #215,650,0.5,0.5,0.5,None,80.000
27,869aa3urj,DIANA (23 Cloncurry Street) #207,14850,10.8,9.8,8.8,None,2596.120
28,869a9ujjg,GEORGE FLAT,3000,2,2,2,None,1057.090
29,869a9uhvd,EXEL (7A SCHUBERT ROAD SW15 2QT) #210,3040,2,2,2,None,192.210
30,869a9a7rn,FRANCESCA (46 HORNTON STREET ),180,0.2,0.2,0.2,None,0.000
31,869a61xwk,MARTIN BROWNE (46 WATERFORD ROAD) #205,1420,0.5,0.5,0.5,None,128.380
32,869a588v6,MARTIN (46 WATERFORD ROAD) #204,270,0.2,None,0.2,None,80.000
33,869a4xzde,GEORGE CLARKE (15 BEDFORD ROAD W4 1JD) #208,37240,23,20,20,5,3315.360
34,869a404c4,VICTORIA NGUYEN 60 EATONS MEWS NORTH #203,None,8,19,19,None,2616.690
35,869a2vhc1,SIMON ROBBIE (98 SUGDEN ROAD) #201,3241,4,0,4,0,581.380
36,869a12e5z,DAVID (SUPPLY & INSTALL TIMBER STUD) 15 DEANS ...,4250,1,1,1,0,NaN
37,8699zaq36,LAURA (40 STOKENCHURCH STREET) #202,2400,2,2,2,None,202.480
38,8699w2nyd,PARSONS NOSE BELGRAVIA (FIX SINK & PIPE) 81 EB...,350,1,0,0,0,NaN
39,8699w2977,"LEILA (9 QUEEN'S MEWS, W2 4BZ) #202",2120,3,2,3,None,801.920
40,8699qnfnk,PETER SINCLAIR (14 Royston Court Hook Rise Nor...,2480,2,2,2,None,180.000
41,8699nmjq2,MARTIN 46 WATERFORD ROAD #198,1000,1,0,0,0,82.400
42,8699ftxm9,ANNA (PAINTING) 45 CALDERVALE ROAD #189,590,0.5,0,0,0.5,85.000
43,8699cky12,KATE 35 CLONCURRY STREET #300,2600,2,2,2,None,378.400
44,86999z3pc,PARSONS NOSE SCOTLAND,11000,6,13,13,0,0.000
45,86999ywg8,TOM KING 103 NEW KINGS ROAD #194,5575,4,0,0,8,3111.930
46,86999yv2u,KENDALL (ONE DAY) 12 DONARELLE STREET #171,1000,0,0.5,0.5,0,91.080
47,869937qtr,FRANCESCA (BEDROOM & BASEMENT REPAIR) 46 HORNT...,2100,2,2,2,0,546.040
48,8698za3ft,BECKS 13 RODWAY ROAD #187,4620,2,2,1,0,0.000
49,8698wc2m7,SIGNE (ROOF WATERPROOFING) 69 RUSHMOLE ROAD #185,6650,3,2,3,0,1301.700
50,8698uwr7k,PARSONS NOSE BELGRAVIA (SHOP RENOVATION) 81 EB...,19000,10,9,8,4,2439.066
51,8698tfzfu,PARSONS NOSE FULHAM (CEILING) 5 HEATHMANS ROAD...,850,1,1,1,0,NaN
52,8698nkayw,SHABHAN (LOFT PROJECT) 36 KERSLEY STREET,6000,14,14,13,0,4806.300
53,8698m1cnu,KATE (ROOFING) 35 CLONCURRY STREET #178,1600,1,1,1,0,486.310
54,8698kr47j,LOTTIE DUNNE (PAINT) 8 DONARELLE STREET #176,650,0,1,1,0,79.800
55,8698kr34y,PARSONS NOSE FULHAM (FRAM BOX) 5 HEATHMANS ROA...,460,0.5,0.5,0.5,0,94.070
56,8698kqvp0,SIOBHAN (LIGHT WELLS) 33 CLONCURRY STREET #174,660,1,1.5,1.5,0,152.500

## Export

In [45]:
# export.py
import pandas as pd

def export_to_excel(projects_df, materials_df, services_df, filename="/Users/madalinasamoila/besa_pipeline/data/raw/raw_data.xlsx"):
    with pd.ExcelWriter(filename, engine="xlsxwriter") as writer:
        projects_df.to_excel(writer, sheet_name="Projects", index=False)
        materials_df.to_excel(writer, sheet_name="Materials", index=False)
        services_df.to_excel(writer, sheet_name="Services", index=False)
        labor_df.to_excel(writer, sheet_name="Labor", index=False)
    print(f"✅ Data exported to {filename}")

In [47]:
import pandas as pd

def export_clean_tables_to_excel(
    client_dim,
    project_dim,
    project_fact,
    expense_fact,
    daily_labor_fact,
    filename="/Users/madalinasamoila/besa_pipeline/data/clean/clean_data.xlsx"
):
    tables = {
        "ClientDim": client_dim,
        "ProjectDim": project_dim,
        "ProjectFact": project_fact,
        "ExpenseFact": expense_fact,
        "DailyLaborFact": daily_labor_fact
    }

    with pd.ExcelWriter(filename, engine="xlsxwriter") as writer:
        for sheet_name, df in tables.items():
            if df is not None and not df.empty:
                df.to_excel(writer, sheet_name=sheet_name, index=False)
                worksheet = writer.sheets[sheet_name]

                # Auto-adjust column widths
                for i, col in enumerate(df.columns):
                    max_len = df[col].astype(str).map(len).max()
                    max_len = max(max_len, len(col)) + 2  # padding
                    worksheet.set_column(i, i, max_len)

    print(f"✅ Clean dimension/fact tables exported to {filename}")